"""Load skills from disk — `skill.yaml` only, never from prose.

The existing `providers/skills.py` walks a tree for `SKILL.md` and parses its
frontmatter. That stays, and it is correct for what it does: it discovers
upstream material and declares it `backend="none"`, which is an honest statement
that the file specifies a skill for a host agent rather than being one we can
run.

This loader is for the other path, the one ADR-0003 describes. A skill is
compiled from `skill.yaml`, and `SKILL.md` is read only to be attached to the
artifact as documentation. If a directory contains a `SKILL.md` and no
`skill.yaml`, this loader says so in a specific, actionable way rather than
silently ignoring the directory:

    CandidateSkillNeedsAdapter: no skill.yaml in .../foo; an upstream SKILL.md
    must be wrapped by a reviewed adapter before it can be compiled

That message is the whole point. The monthly Scout will meet thousands of
`SKILL.md`-only directories, and the failure mode to avoid is treating them as
loadable because they look like skills.
"""

from __future__ import annotations

import hashlib
from dataclasses import dataclass
from pathlib import Path
from typing import Iterator

from .models import SkillSpec, spec_from_dict

__all__ = ["CandidateSkillNeedsAdapter", "LoadedSkill", "RunContractManifest", "SkillLoadError",
           "entrypoint_module_path", "is_run_contract", "load_skill_dir", "load_skills",
           "skill_content_hash", "skill_dependency_closure"]

SKILL_FILE = "skill.yaml"
DOC_FILE = "SKILL.md"


class SkillLoadError(ValueError):
    """A skill directory could not be loaded, with the reason."""


class CandidateSkillNeedsAdapter(SkillLoadError):
    """A directory holds `SKILL.md` but no `skill.yaml`.

    Distinct from a plain load error because the remedy is different and
    specific: write and review an adapter. The monthly Scout counts these
    separately — they are the candidate backlog, not failures.
    """


@dataclass(frozen=True, slots=True)
class LoadedSkill:
    """A skill and where it came from."""

    spec: SkillSpec
    directory: Path
    content_hash: str
    documentation: str = ""

    @property
    def id(self) -> str:
        return self.spec.id

    @property
    def composite_id(self) -> str:
        return self.spec.composite_id


def skill_content_hash(directory: Path, *, entrypoint: str = "") -> str:
    """SHA-256 over every file a skill is built from — manifest *and* code.

    Two sets of files, and missing the second is a hole rather than an
    inconvenience. The skill directory holds `skill.yaml`, but for a Python
    skill the implementation lives wherever `runtime.entrypoint` points — in this
    repository, `src/bioagent/skills/p0/`. A hash over the directory alone pins
    the *declaration* and leaves the behaviour editable, so an upstream (or
    local) change to the implementation would not move the pin. This was found
    by a test that edited a skill's implementation and watched the lockfile check
    pass when it should have failed.

    The code set is the entry module plus its local import closure (see
    :func:`skill_dependency_closure`), so a change to a helper the skill calls
    moves the pin as surely as a change to the entry file. Shared helpers mean a
    change to, say, the contract layer moves every skill's pin — correct, since
    every skill's behaviour changed.

    Excludes `SKILL.md`, which is documentation and cannot affect behaviour, and
    `__pycache__`, which is derived.
    """
    directory = Path(directory).resolve()
    module = entrypoint_module_path(entrypoint)
    root = (_package_root(module, entrypoint.split(":", 1)[0].strip())
            if module is not None else None)
    digest = hashlib.sha256()
    for path in _hashed_files(directory, entrypoint):
        # The name that enters the digest is always relative to a *resolved*
        # base, never derived from how the caller spelled the path. An earlier
        # version used `relative_to(directory)` on the argument as given, so
        # `skills/tcm/x` and `/abs/skills/tcm/x` — the same tree — produced
        # different digests, and a lockfile generated by one caller failed to
        # verify under another. A pin that depends on the caller is not a pin.
        if _within(path, directory):
            rel = path.relative_to(directory).as_posix()
        elif root is not None and _within(path.resolve(), root):
            rel = path.resolve().relative_to(root).as_posix()
        else:
            rel = path.name
        digest.update(rel.encode("utf-8"))
        digest.update(b"\0")
        digest.update(path.read_bytes())
        digest.update(b"\0")
    return digest.hexdigest()


def _hashed_files(directory: Path, entrypoint: str) -> list[Path]:
    """The files that make up a skill: its directory, plus its implementation."""
    paths: list[Path] = []
    for path in sorted(directory.rglob("*")):
        if not path.is_file():
            continue
        if "__pycache__" in path.parts or path.name == DOC_FILE:
            continue
        if path.name.endswith((".pyc", ".pyo")):
            continue
        paths.append(path)

    module = entrypoint_module_path(entrypoint)
    if module is not None and module.is_file():
        # The entry module *and everything it imports from its own top-level
        # package*, transitively. Hashing the entry file alone pinned
        # "this file changed", not "this skill's behaviour changed": a skill
        # whose logic sat in an imported helper could be edited with the pin
        # unmoved (audit F08). Imports outside the package — the standard
        # library and third-party distributions — are pinned by the
        # environment, not by this digest, and are reported by
        # `skill_dependency_closure` so a caller can see the boundary.
        paths.extend(_import_closure(module, entrypoint.split(":", 1)[0].strip()))
    return sorted(set(paths))


def skill_dependency_closure(entrypoint: str) -> tuple[Path, ...]:
    """The local source files a Python entrypoint's behaviour depends on.

    Found statically: every ``import``/``from … import`` in the entry module, and
    in each module it reaches, that resolves inside the entry's own top-level
    package. Dynamic imports (``importlib.import_module`` with a computed name)
    are invisible to this walk — a skill must not depend on one.
    """
    module = entrypoint_module_path(entrypoint)
    if module is None or not module.is_file():
        return ()
    return tuple(sorted(_import_closure(module, entrypoint.split(":", 1)[0].strip())))


def _import_closure(entry: Path, module_name: str) -> set[Path]:
    import ast

    top = module_name.split(".", 1)[0]
    root = _package_root(entry, module_name)
    if root is None:
        return {entry}
    seen: set[Path] = set()
    stack: list[tuple[Path, str]] = [(entry, module_name)]
    while stack:
        path, name = stack.pop()
        path = path.resolve()
        if path in seen or not path.is_file():
            continue
        seen.add(path)
        is_pkg = path.name == "__init__.py"
        package = name if is_pkg else name.rpartition(".")[0]
        # A module's enclosing packages' __init__ run before it; their code is
        # behaviour too.
        enclosing = name.rpartition(".")[0] if is_pkg else package
        if enclosing:
            init = _module_file(root, enclosing)
            if init is not None:
                stack.append((init, enclosing))
        try:
            tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
        except (SyntaxError, UnicodeDecodeError):
            continue
        for node in ast.walk(tree):
            targets: list[str] = []
            if isinstance(node, ast.Import):
                targets = [a.name for a in node.names]
            elif isinstance(node, ast.ImportFrom):
                if node.level:
                    parts = package.split(".") if package else []
                    if node.level - 1 > len(parts):
                        continue
                    base = parts[:len(parts) - (node.level - 1)]
                    prefix = ".".join(base + ([node.module] if node.module else []))
                else:
                    prefix = node.module or ""
                targets = [prefix] + [f"{prefix}.{a.name}" for a in node.names
                                      if a.name != "*"]
            for target in targets:
                if not target or target.split(".", 1)[0] != top:
                    continue
                found = _module_file(root, target)
                if found is not None:
                    stack.append((found, target))
    return seen


def _package_root(entry: Path, module_name: str) -> Path | None:
    """The directory that holds the top-level package of ``module_name``."""
    entry = entry.resolve()
    depth = module_name.count(".") + (1 if entry.name == "__init__.py" else 0)
    root = entry.parent
    for _ in range(depth):
        root = root.parent
    return root if (root / module_name.split(".", 1)[0]).exists() else None


def _module_file(root: Path, dotted: str) -> Path | None:
    base = root.joinpath(*dotted.split("."))
    for candidate in (base.with_suffix(".py"), base / "__init__.py"):
        if candidate.is_file():
            return candidate
    return None


def _within(path: Path, directory: Path) -> bool:
    try:
        path.relative_to(directory)
        return True
    except ValueError:
        return False


def entrypoint_module_path(entrypoint: str) -> Path | None:
    """Resolve a `module.path:callable` entrypoint to its source file, or None.

    Returns ``None`` rather than raising for an entrypoint this process cannot
    resolve — a skill whose implementation is installed elsewhere is hashed over
    its directory alone, and that is reported by the caller rather than silently
    producing a hash that looks complete.
    """
    if not entrypoint or ":" not in entrypoint:
        return None
    module_name = entrypoint.split(":", 1)[0].strip()
    if not module_name:
        return None
    try:
        import importlib.util
        spec = importlib.util.find_spec(module_name)
    except (ImportError, ValueError, ModuleNotFoundError):
        return None
    if spec is None or not spec.origin or spec.origin in ("built-in", "frozen"):
        return None
    return Path(spec.origin)


#: Keys of the other ``skill.yaml`` this tree holds: a run contract read by
#: ``providers.skills.SkillContract`` (a skill run under ``bioagent.analysis``, with
#: its own steps, sources and claim ceiling). It carries no ``api_version``.
_RUN_CONTRACT_KEYS = frozenset({"requires", "steps", "max_claim_kind"})


class RunContractManifest(SkillLoadError):
    """The ``skill.yaml`` is a run contract (``providers.skills``), not a registry manifest."""


def is_run_contract(raw: object) -> bool:
    """A manifest with no ``api_version`` and the keys of a run contract.

    Recognised by both conditions, not by the absent version alone: a registry
    manifest that merely forgot ``api_version`` must still be refused as one.
    """
    return (isinstance(raw, dict) and "api_version" not in raw
            and bool(_RUN_CONTRACT_KEYS & set(raw)))


def load_skill_dir(directory: Path | str, *, require_implementation: bool = False
                   ) -> LoadedSkill:
    """Load one skill directory.

    ``require_implementation`` refuses a `python` skill whose entrypoint module
    is not present in the tree — the check that stops a manifest from pointing at
    code that does not exist, which would only surface at first invocation.
    """
    directory = Path(directory)
    if not directory.is_dir():
        raise SkillLoadError(f"{directory} is not a directory")

    manifest = directory / SKILL_FILE
    if not manifest.is_file():
        if (directory / DOC_FILE).is_file():
            raise CandidateSkillNeedsAdapter(
                f"no {SKILL_FILE} in {directory}; an upstream {DOC_FILE} must be "
                "wrapped by a reviewed adapter before it can be compiled")
        raise SkillLoadError(f"no {SKILL_FILE} or {DOC_FILE} in {directory}")

    import yaml  # imported here so the module loads without PyYAML present

    try:
        raw = yaml.safe_load(manifest.read_text(encoding="utf-8")) or {}
    except yaml.YAMLError as exc:
        raise SkillLoadError(f"{manifest}: invalid YAML: {exc}") from exc
    if not isinstance(raw, dict):
        raise SkillLoadError(f"{manifest}: expected a mapping at the top level")
    if is_run_contract(raw):
        raise RunContractManifest(
            f"{manifest} is a run contract (providers.skills.SkillContract), not a "
            "registry manifest")

    spec = spec_from_dict(raw, origin=str(directory))

    if require_implementation and spec.runtime.backend == "python":
        # Resolved through the import system, not relative to the skill
        # directory: an entrypoint is a dotted module path, and for every skill
        # in this repository the implementation lives in the package rather than
        # beside the manifest. Looking next to `skill.yaml` would have failed to
        # find code that is present and importable.
        resolved = entrypoint_module_path(spec.runtime.entrypoint)
        if resolved is None or not resolved.is_file():
            on_disk = directory / (spec.runtime.entrypoint.split(":", 1)[0]
                                   .replace(".", "/") + ".py")
            raise SkillLoadError(
                f"skill {spec.id!r} declares entrypoint {spec.runtime.entrypoint!r} "
                f"but it resolves to no source file (looked up as a module, and at "
                f"{on_disk})")

    doc = ""
    doc_path = directory / DOC_FILE
    if doc_path.is_file():
        doc = doc_path.read_text(encoding="utf-8", errors="replace")

    # The hash covers the manifest *and* the implementation the entrypoint
    # names, so it must be taken after the spec is parsed. Hashing the directory
    # alone would pin the declaration and leave the behaviour editable.
    digest = skill_content_hash(directory, entrypoint=spec.runtime.entrypoint)
    spec = _with_hash(spec, digest)
    return LoadedSkill(spec=spec, directory=directory, content_hash=digest,
                       documentation=doc)


def load_skills(root: Path | str, *, require_implementation: bool = False
                ) -> tuple[tuple[LoadedSkill, ...], tuple[tuple[Path, str], ...]]:
    """Load every skill under ``root``.

    Returns ``(loaded, refused)`` rather than raising on the first bad
    directory. A run contract (see ``is_run_contract``) is neither: it belongs to
    the other loader and is skipped. A registry build must see the whole set: one malformed third-party
    skill should not stop the other nineteen from being audited, and the refused
    list is audit output in its own right.
    """
    root = Path(root)
    loaded: list[LoadedSkill] = []
    refused: list[tuple[Path, str]] = []
    if not root.is_dir():
        return (), ((root, f"{root} is not a directory"),)
    for directory in sorted(p for p in root.iterdir() if p.is_dir()):
        if not (directory / SKILL_FILE).is_file() and not (directory / DOC_FILE).is_file():
            continue
        try:
            loaded.append(load_skill_dir(directory,
                                         require_implementation=require_implementation))
        except RunContractManifest:
            continue
        except SkillLoadError as exc:
            refused.append((directory, str(exc)))
    return tuple(loaded), tuple(refused)


def _with_hash(spec: SkillSpec, digest: str) -> SkillSpec:
    """A copy of ``spec`` carrying ``digest``. Frozen dataclasses have no setter."""
    from dataclasses import replace
    return replace(spec, content_hash=digest)
