// UI strings, zh (primary) and en (complete). Registered with core/i18n at startup. The governance vocabulary
// (claim kinds, tiers, states, codes) comes from core/glossary.js and is never retranslated here.
// Microcopy rules: DESIGN §7 — exact before fluent, never overclaim, a refusal is a result (no apology, no "!"),
// numbers carry units, absence is said out loud.

import { registerStrings } from "../core/i18n.js";

export const ZH = {
  // common actions
  "ui.action.cancel": "取消",
  "ui.action.close": "关闭",
  "ui.action.confirm": "确定",
  "ui.action.copy": "复制",
  "ui.action.save": "保存",
  "ui.action.open_inspector": "在检查器中打开",
  "ui.common.yes": "是",
  "ui.common.no": "否",
  "ui.toast.copied": "已复制",
  "ui.toast.copy_failed": "无法复制：浏览器不允许访问剪贴板",

  // hashes
  "ui.hash.aria": "{visible}（完整值 {value}）。复制哈希",
  "ui.hash.copied": "已复制完整哈希",
  "ui.hash.none": "无哈希",

  // families, ladder
  "ui.family.predicted_tip": "这是计算预测，不是测量结果。它最多支撑机制假说。",
  "ui.family.unknown": "未知种类",
  "ui.ladder.licenses": "可支撑此主张类型",
  "ui.ladder.weakest": "本主张最弱的证据",
  "ui.ladder.no_weakest": "主张类型：{kind} —— 没有可判定的证据等级",

  // claims
  "ui.claim.kind_tip": "主张类型：决定需要哪类证据才能支撑它",
  "ui.claim.supports": "依据",
  "ui.claim.no_support": "未引用任何证据",
  "ui.claim.remedy": "可以这样处理",
  "ui.claim.weakest": "最弱一环",
  "ui.claim.weakest_short": "最弱：{tier}",
  "ui.claim.caveats": "说明 {n} 条",
  "ui.claim.caveats_short": "说明 {n} 条",
  "ui.claim.extrapolations": "未经证据验证的外推 {n} 处",
  "ui.claim.extrap_short": "外推 {n} 处",
  "ui.claim.falsified_by": "什么会推翻它",
  "ui.claim.falsified_by_none": "未说明",
  "ui.claim.falsify_short": "可被推翻：{text}",
  "ui.claim.confidence": "置信度",
  "ui.claim.basis": "依据：{basis}",
  "ui.claim.no_basis": "未说明依据",

  // release, artifact, composite version
  "ui.release.met": "已满足",
  "ui.release.unmet": "未满足",
  "ui.release.details": "六项发布状态",
  "ui.artifact.untitled": "产物",
  "ui.artifact.status_tip": "产物状态：Skill 自己报告的工作流状态，未经人工验证；是否准予发布由内核判定。",
  "ui.artifact.output_verified": "已核验",
  "ui.artifact.limitations": "局限 {n} 条",
  "ui.artifact.no_limitations": "未声明局限：按约定，这样的产物无效（ART110）",
  "ui.artifact.more_limits": "另有 {n} 条，见检查器",
  "ui.artifact.warnings": "警告 {n} 条",
  "ui.artifact.violations": "未通过的检查 {n} 项",
  "ui.artifact.assumptions": "假设",
  "ui.artifact.none": "无",
  "ui.artifact.not_attested": "未经审计链证明",
  "ui.cv.title": "复合版本",
  "ui.cv.runtime": "运行时",
  "ui.cv.skill": "Skill",
  "ui.cv.source": "数据源",
  "ui.cv.benchmark": "基准",
  "ui.cv.unversioned": "未版本化",

  // evidence, quality, sources, citations
  "ui.quality.risk_of_bias": "偏倚风险",
  "ui.quality.directness": "直接性",
  "ui.quality.precision": "精确性",
  "ui.quality.consistency": "一致性",
  "ui.quality.not_assessed": "未评估",
  "ui.quality.none": "质量四项均未评估",
  "ui.evidence.quote_verified": "引文已核对",
  "ui.evidence.quote_unverified": "引文未核对",
  "ui.evidence.quote_verified_short": "已核对",
  "ui.evidence.quote_unverified_short": "未核对",
  "ui.evidence.conflicts": "与 {n} 条证据冲突",
  "ui.evidence.source_tip": "数据源卡片",
  "ui.evidence.source_missing": "卡片不在产物中",
  "ui.evidence.table_label": "证据表",
  "ui.evidence.col.design": "种类 · 设计",
  "ui.evidence.col.citation": "出处",
  "ui.evidence.col.quote": "引文",
  "ui.evidence.col.retraction": "撤稿",
  "ui.evidence.col.hash": "内容哈希",
  "ui.source.licence": "许可",
  "ui.source.unlicensed": "未声明许可",
  "ui.source.kind": "类型",
  "ui.source.access": "获取方式",
  "ui.source.snapshot": "快照",
  "ui.source.unpinned": "未固定快照",
  "ui.source.offline": "可离线",
  "ui.source.limits": "已知局限",
  "ui.cite.aria": "证据 {id}：{label}",
  "ui.cite.unknown": "{id}：本轮工具结果中没有这条引用",

  // thinking
  "ui.think.title": "思考",
  "ui.think.live": "思考中 · {s} 秒",
  "ui.think.done": "思考 · {d}",
  "ui.think.note": "模型的思考过程不是证据，也不会作为引用。",

  // where it ran
  "ui.where.browser": "浏览器",
  "ui.where.runner": "本机 Runner",
  "ui.where.relay": "中继",
  "ui.where.browser_short": "浏览器中",
  "ui.where.runner_short": "本机",
  "ui.where.decided_in_page": "由页面判定，工具没有运行",
  "ui.where.not_run": "未运行",
  "ui.release.more": "另有 {n} 条，见检查器",

  // tool cards
  "ui.tool.running_at": "正在{place}运行 {name} · {device}",
  "ui.tool.preparing": "正在准备调用 {name}…",
  "ui.tool.waiting_approval": "尚未运行",
  "ui.tool.claims_refused": "{n} 条主张已拒绝",
  "ui.tool.args": "参数",
  "ui.tool.args_json": "完整参数（JSON）",
  "ui.tool.result": "结果（前几行）",
  "ui.tool.more_lines": "另有 {n} 行，在检查器中查看完整结果",
  "ui.tool.input": "输入",
  "ui.tool.output": "输出",
  "ui.tool.not_durable": "审计状态只保存在内存中",

  // permission
  "ui.perm.title": "需要你的批准",
  "ui.perm.title_decided": "批准记录",
  "ui.perm.network": "将访问网络上的这些主机：",
  "ui.perm.no_hosts": "（未声明主机）",
  "ui.perm.job": "将在本机 Runner 上启动任务：{what}。任务在你的电脑上运行，可随时取消；完成并核验之前，它的输出不会作为结果。",
  "ui.perm.confirm": "这是需要确认的操作：{what}。",
  "ui.perm.remote_upload": "将把数据发送到第三方服务，数据会离开你的电脑：",
  "ui.perm.first_runner": "这是本项目第一次在本机 Runner 上运行工具。Runner 运行在 127.0.0.1，数据不离开你的电脑。",
  "ui.perm.once": "允许一次",
  "ui.perm.project": "本项目允许",
  "ui.perm.deny": "拒绝",
  "ui.perm.decided.once": "已允许一次",
  "ui.perm.decided.project": "已在本项目中允许",
  "ui.perm.decided.deny": "未批准 · 未运行",

  // jobs
  "ui.job.step.submitted": "已提交",
  "ui.job.step.running": "运行中",
  "ui.job.step.collected": "已收集并核验",
  "ui.job.progress": "任务进度",
  "ui.job.pending_note": "任务完成并核验之前，它的输出不会作为结果显示。",
  "ui.job.no_result": "这个任务没有结果。",
  "ui.job.failed": "任务未完成。",
  "ui.job.cancel": "取消任务",
  "ui.job.logs": "日志 {n} 行",
  "ui.job.kind.pipeline.rnaseq": "RNA-seq 流程",
  "ui.job.kind.pipeline.scrna": "单细胞流程",
  "ui.job.kind.pipeline.fold": "蛋白结构预测",
  "ui.job.kind.pipeline.dock": "分子对接",
  "ui.job.kind.pipeline.admet": "ADMET 预测",
  "ui.job.kind.research.run": "网络药理学研究闭环",
  "ui.job.kind.skill.run": "受治理的 Skill 运行",
  "ui.job.kind.tcmdb.fetch": "下载中医药数据集",
  "ui.job.kind.tcmdb.build": "构建本地数据库",
  // theme
  "ui.theme.system": "跟随系统",
  "ui.theme.light": "浅色",
  "ui.theme.dark": "深色",

  // gallery (design QA)
  "ui.gallery.title": "组件陈列 · 设计检查",
  "ui.gallery.workspace": "工作区",
  "ui.gallery.workspace_lede": "对话、工具卡、主张与产物卡、分支切换（‹1/2›）和检查器，由应用自己的模块渲染；工具结果是上面那些真实运行的信封。",
  "ui.gallery.composer": "输入框",
  "ui.gallery.panels": "计算与模型面板",
  "ui.gallery.project": "项目概览",
  "ui.gallery.primitives": "基础组件",
  "ui.gallery.governance": "治理视觉语言",
  "ui.gallery.claims": "主张",
  "ui.gallery.artifacts": "产物与发布状态",
  "ui.gallery.evidence": "证据",
  "ui.gallery.run": "运行透明度",
  "ui.gallery.jobs": "任务",
  "ui.gallery.tokens_lede": "设计令牌（DESIGN §5）。每个颜色在浅色与深色下都经过对比度检查。",
  "ui.gallery.kicker": "治理层",
  "ui.gallery.open_menu": "菜单",
  "ui.gallery.open_popover": "浮层",
  "ui.gallery.open_dialog": "对话框",
  "ui.gallery.claims_lede": "下面的主张由内核实际判定（validate_artifact）：一条疗效主张只依赖细胞实验（CLM005），一条把对接预测当作事实（CLM004），一条机制假说获准，附说明。",

  // app (generated sections: shell, conversation, inspector, pages)
  "ui.action.create": "创建",
  "ui.action.delete": "删除",
  "ui.action.later": "稍后",
  "ui.action.rename": "重命名",
  "ui.action.retry": "重试",
  "ui.action.undo": "撤销",
  "ui.skip.composer": "跳到输入框",
  "ui.skip.main": "跳到主要内容",
  "ui.toasts.label": "通知",
  "ui.toast.code_copied": "已复制代码",
  "ui.code.wrap": "换行",
  "ui.project.approval.runner": "在本机 Runner 上运行工具",
  "ui.project.approval.network": "联网",
  "ui.project.approval.remote": "发送数据到第三方服务",
  "ui.project.approval.run": "运行（任务或需确认的操作）",
  "ui.skip.thread": "跳到对话",
  "ui.boot.loading": "正在载入…",
  "ui.storage.memory": "这个浏览器不允许本站使用 IndexedDB（例如无痕窗口），项目和会话只保存在内存中，关闭页面后不会保留。",
  "ui.toast.answer_copied": "已复制回答（Markdown，含引用）",
  "ui.nav.new_chat": "新建会话",
  "ui.nav.search": "搜索",
  "ui.nav.settings": "设置",
  "ui.nav.about": "关于",
  "ui.nav.catalog": "工具目录",
  "ui.notfound.title": "没有这个页面",
  "ui.notfound.body": "地址不对，或者它指向的数据只保存在另一台设备的浏览器里。",
  "ui.notfound.home": "回到首页",
  "ui.sidebar.label": "项目与会话",
  "ui.sidebar.toggle": "切换侧栏",
  "ui.sidebar.more": "更多",
  "ui.sidebar.projects": "项目",
  "ui.sidebar.recent": "最近会话",
  "ui.sidebar.conversations": "本项目的会话",
  "ui.sidebar.conversations_in": "{name} 的会话",
  "ui.sidebar.no_projects": "还没有项目。发送第一条消息时会自动创建一个。",
  "ui.sidebar.no_conversations": "还没有会话。",
  "ui.sidebar.archived": "已归档 {n} 个",
  "ui.sidebar.group.pinned": "已置顶",
  "ui.sidebar.group.today": "今天",
  "ui.sidebar.group.yesterday": "昨天",
  "ui.sidebar.group.week": "过去 7 天",
  "ui.sidebar.group.older": "更早",
  "ui.topbar.breadcrumb": "当前位置",
  "ui.topbar.project_tip": "项目概览",
  "ui.topbar.rename_tip": "重命名会话",
  "ui.lang.switch": "切换语言（中文 / English）",
  "ui.theme.title": "外观",
  "ui.theme.switch": "外观：{theme}",
  "ui.inspector.label": "检查器",
  "ui.inspector.toggle": "检查器",
  "ui.inspector.tabs": "检查器分页",
  "ui.inspector.close": "关闭检查器",
  "ui.inspector.resize": "调整检查器宽度",
  "ui.inspector.expand": "展开到全屏",
  "ui.inspector.collapse": "收起",
  "ui.inspector.scope": "范围",
  "ui.inspector.scope_turn": "此回答",
  "ui.inspector.scope_all": "整个会话",
  "ui.inspector.goto_turn": "在对话中定位",
  "ui.inspector.tab.run": "过程",
  "ui.inspector.tab.evidence": "证据",
  "ui.inspector.tab.claims": "主张",
  "ui.inspector.tab.files": "文件",
  "ui.inspector.tab.provenance": "溯源",
  "ui.inspector.empty.run_title": "还没有运行记录",
  "ui.inspector.empty.run": "模型调用工具后，这里会按顺序列出每一步：思考、工具运行、你的批准、发布门检查。",
  "ui.inspector.empty.evidence_title": "还没有证据",
  "ui.inspector.empty.evidence": "运行工具后，这里会列出每条证据、它的种类和来源快照。",
  "ui.inspector.empty.claims_title": "还没有主张",
  "ui.inspector.empty.claims": "工具返回主张时，这里会列出每条主张、内核的判定和理由代码。被拒绝的主张也会留在这里。",
  "ui.inspector.empty.prov_title": "还没有可溯源的运行",
  "ui.inspector.empty.prov": "运行工具后，这里会显示复合版本、数据源快照、审计链头和复现命令。",
  "ui.conv.untitled": "未命名会话",
  "ui.conv.rename": "重命名会话",
  "ui.conv.menu": "会话「{name}」的操作",
  "ui.conv.pin": "置顶",
  "ui.conv.unpin": "取消置顶",
  "ui.conv.delete_title": "删除会话",
  "ui.conv.delete_body": "删除「{name}」及其全部消息和工具结果。只删除本浏览器中的副本，无法撤销。",
  "ui.conv.missing": "找不到这个会话：它可能已被删除，或保存在另一台设备的浏览器里。",
  "ui.project.default_name": "我的研究",
  "ui.project.kicker": "项目",
  "ui.project.empty_title": "新项目",
  "ui.project.empty_body": "写下研究问题，或从下面的示例开始。每个示例都会展示一次内核的拒绝。",
  "ui.project.new": "新建项目",
  "ui.project.name": "项目名称",
  "ui.project.name_ph": "例如：葛根芩连汤 · 网络药理学复核",
  "ui.project.rename": "重命名项目",
  "ui.project.menu": "项目「{name}」的操作",
  "ui.project.edit_desc": "编辑项目描述",
  "ui.project.export": "导出项目",
  "ui.project.exported": "已导出项目（JSON，含文件与哈希）",
  "ui.project.archive": "归档",
  "ui.project.unarchive": "取消归档",
  "ui.project.archived": "已归档「{name}」",
  "ui.project.delete_title": "删除项目「{name}」",
  "ui.project.delete_body": "删除这个项目的全部会话、消息和知识文件。只删除本浏览器中的副本，无法撤销。需要保留时，请先导出。",
  "ui.project.missing": "找不到这个项目：它可能已被删除，或保存在另一台设备的浏览器里。",
  "ui.project.save_failed": "项目设置没有保存：{message}。显示的是浏览器里保存的设置。",
  "ui.project.conversations": "会话",
  "ui.project.instructions": "项目说明",
  "ui.project.instructions_ph": "例如：回答时区分记载、预测与实测；优先引用《中国药典》。",
  "ui.project.instructions_help": "每次对话都会附在系统提示之后。它约束模型怎么说，但不能放宽内核的判定。",
  "ui.project.saving": "保存中…",
  "ui.project.saved": "已保存",
  "ui.project.defaults": "默认设置",
  "ui.project.default_model": "默认模型",
  "ui.project.default_model_help": "本项目新会话使用的模型；单个会话仍可在输入框旁切换。",
  "ui.project.default_compute": "计算目标",
  "ui.project.default_compute_help": "本项目的工具在哪里运行。",
  "ui.project.follow_global": "跟随全局设置",
  "ui.project.approvals": "本项目已批准的操作",
  "ui.project.approvals_help": "这些操作在本项目中不再逐次询问。撤销后，下次运行会重新请求批准。",
  "ui.project.revoke": "撤销",
  "ui.project.recent_claims": "近期主张",
  "ui.project.no_claims": "这个项目还没有产生主张。",
  "ui.examples.label": "示例",
  "ui.examples.runner_chip": "需要本机 Runner",
  "ui.examples.needs_runner": "这个示例需要本机 Runner。",
  "ui.examples.normalize.prompt": "规范化：姜、白芍",
  "ui.examples.normalize.shows": "歧义被保留：「姜」可能是生姜，也可能是干姜，不替你选择。",
  "ui.examples.network.prompt": "桂枝汤的组成与靶点：语料里记载了什么",
  "ui.examples.network.shows": "种子语料没有靶点记录：列出组成和记载的主治，不构建网络、不提出主张；实测靶点需要本机 Runner 的网络药理任务。",
  "ui.examples.safety.prompt": "甘草与甘遂同用，有哪些记载？",
  "ui.examples.safety.shows": "十八反配伍：报告为记载，不是临床安全信号。",
  "ui.examples.evidence.prompt": "附子的现有证据有哪些？按证据种类分组",
  "ui.examples.evidence.shows": "只报告证据及其种类，不替证据下结论。",
  "ui.examples.enrichment.prompt": "复核葛根芩连汤的网络药理学富集：以实际被检测的蛋白为背景",
  "ui.examples.enrichment.shows": "复现项目主页的案例：背景集改变后，富集结论随之改变。",
  "ui.composer.label": "输入消息",
  "ui.composer.placeholder": "提问，或描述要做的分析…",
  "ui.composer.placeholder_hero": "写下研究问题…",
  "ui.composer.placeholder_streaming": "回答生成中，可以先写下一条…",
  "ui.composer.attach": "添加文件",
  "ui.composer.attachments": "附件",
  "ui.composer.send": "发送",
  "ui.composer.stop": "停止生成",
  "ui.composer.stop_tip": "停止生成（Esc）",
  "ui.composer.options": "模型与计算",
  "ui.composer.foot": "模型负责推理；证据能支撑哪类主张，由内核判定。",
  "ui.composer.drop": "松开以添加文件",
  "ui.composer.drop_note": "文件只保存在本浏览器，不会上传到 science.impf.ai。但 8 KB 以下的文本文件会随本项目的每条消息发送给所选模型（Tao-S1 经 science.impf.ai 中继转给模型服务）；其他文件只有在你发送到本机 Runner 时才离开这台设备。",
  "ui.composer.hashing": "计算哈希 {p}%",
  "ui.composer.hash_failed": "无法读取文件",
  "ui.composer.wait_hash": "请等附件的哈希计算完成。",
  "ui.composer.remove": "移除 {name}",
  "ui.composer.big_file": "大于 200 MB：建议发送到本机 Runner 处理。",
  "ui.model.title": "模型",
  "ui.model.chip_tip": "选择模型",
  "ui.model.default": "默认",
  "ui.model.tao_sub": "经 science.impf.ai 中继 · 无需密钥",
  "ui.model.yours": "你的 API",
  "ui.model.local": "本地模型",
  "ui.model.detected": "{label} · 已检测到",
  "ui.model.detect": "检测本地模型",
  "ui.model.detect_needs_runner": "检测本地模型需要先连接本机 Runner。",
  "ui.model.detected_n": "检测到 {n} 个本地模型服务",
  "ui.model.detected_none": "没有检测到正在运行的本地模型服务。",
  "ui.model.manage": "添加或管理模型",
  "ui.model.this_conv": "仅本会话",
  "ui.model.this_new": "仅新会话",
  "ui.model.relay_ok": "中继可用",
  "ui.model.relay_down": "中继暂不可用",
  "ui.compute.title": "计算",
  "ui.compute.chip_tip": "计算在哪里进行",
  "ui.compute.chip.browser": "浏览器",
  "ui.compute.chip.runner": "本机 · {device}",
  "ui.compute.chip.runner_off": "本机（未连接）",
  "ui.compute.target": "计算目标",
  "ui.compute.auto": "自动",
  "ui.compute.auto_tip": "本机 Runner 已连接时在 Runner 上运行；未连接时，能在浏览器运行的在浏览器运行。",
  "ui.compute.browser": "浏览器",
  "ui.compute.runner": "本机 Runner",
  "ui.compute.target_help.auto": "本机 Runner 已连接时，工具都在 Runner 上运行（本机 Python、项目的持久审计链、你的设备）；未连接时，能在浏览器运行的工具在浏览器运行，联网、重依赖、GPU 和长任务需要 Runner。",
  "ui.compute.target_help.browser": "只在浏览器中运行；只能在 Runner 上运行的工具会报告「不可用」，不会用近似结果顶替。",
  "ui.compute.target_help.runner": "只在本机 Runner 上运行；Runner 未连接时，工具会报告「不可用」。",
  "ui.compute.project_override": "（「{name}」的项目设置）",
  "ui.compute.browser_runtime": "浏览器",
  "ui.compute.browser_sub": "Pyodide · Web Worker",
  "ui.compute.runner_runtime": "本机 Runner",
  "ui.compute.mobile": "本机 Runner 需要在电脑上运行。手机上，工具在浏览器中运行。",
  "ui.compute.more": "更多计算设置",
  "ui.browser.status.idle": "未加载",
  "ui.browser.status.loading": "加载中",
  "ui.browser.status.connecting": "加载中",
  "ui.browser.status.ready": "就绪",
  "ui.browser.status.error": "出错",
  "ui.browser.status.offline": "不可用",
  "ui.browser.loading": "正在加载 Python 运行环境",
  "ui.browser.idle_note": "首次运行工具时下载 Python 运行环境（约 9 MB，之后从浏览器缓存读取）。",
  "ui.browser.offline_note": "这个页面没有带上浏览器运行环境（构建产物缺失）。连接本机 Runner 后仍可运行工具。",
  "ui.browser.cpu_note": "Python 工具在 CPU 上运行（单线程，WebAssembly）。",
  "ui.browser.cores": "{cores} 个逻辑核心{memory}",
  "ui.browser.memory": " · 约 {gb} GB 内存",
  "ui.browser.webgpu_none": "这个浏览器没有 WebGPU。",
  "ui.browser.webgpu_no_adapter": "浏览器支持 WebGPU，但没有可用的 GPU 适配器（将使用 CPU）。",
  "ui.browser.webgpu_software": "WebGPU 适配器是软件模拟（{name}），不是 GPU。",
  "ui.browser.webgpu_hw": "WebGPU：{name}。兼容的序列统计工具可使用 GPU，并自动回退 CPU。",
  "ui.browser.acceleration": "浏览器加速",
  "ui.browser.acceleration_auto": "自动：选用经过核对的最快方式（兼容工具用 GPU，其次 CPU 内核），否则用原始 Python",
  "ui.browser.acceleration_cpu": "仅 CPU：CPU 内核（JavaScript）和 Python，不使用 GPU",
  "ui.browser.acceleration_reference": "仅原始 Python：每个工具都用原始实现（用于核对结果）",
  "ui.browser.acceleration_help": "计算仅在你主动运行工具时开始。序列距离矩阵、汉明距离和 GC 含量可用 GPU；序列比对、编辑距离和这几项计数还有 CPU 内核。结果与原始 Python 逐字节相同，每个结果都经 Python 核对，回执写明由谁计算。其他 Python 工具在 WebAssembly CPU 上运行。",
  "ui.browser.isolated": "跨源隔离已开启：运行中的 Python 可以被中断。",
  "ui.browser.not_isolated": "跨源隔离未开启：运行中的 Python 只能通过重启 Worker 停止。",
  "ui.browser.preload": "预先加载",
  "ui.runner.status.idle": "未连接",
  "ui.runner.status.offline": "未连接",
  "ui.runner.status.connecting": "连接中",
  "ui.runner.status.ready": "已连接",
  "ui.runner.status.error": "连接失败",
  "ui.runner.unavailable": "运行环境模块不可用。",
  "ui.runner.connected": "已连接本机 Runner",
  "ui.runner.connect": "连接",
  "ui.runner.connecting": "正在连接…",
  "ui.runner.disconnect": "断开",
  "ui.runner.not_connected": "未连接本机 Runner。浏览器内计算仍可用；大文件和 GPU 任务需要 Runner。",
  "ui.runner.how": "在电脑的终端里运行",
  "ui.runner.how_help": "它会打印一个配对链接；打开那个链接即可自动配对。也可以在下面填写地址和令牌。",
  "ui.runner.enter_token": "填写地址和令牌",
  "ui.runner.url": "Runner 地址",
  "ui.runner.token": "配对令牌",
  "ui.runner.token_help": "终端里打印的令牌。它只保存在本浏览器。",
  "ui.runner.cores": "{n} 核",
  "ui.runner.cpu_unknown": "CPU 信息不可用",
  "ui.runner.memory": "内存 {gb} GB",
  "ui.runner.device": "设备",
  "ui.runner.device_auto": "自动选择",
  "ui.runner.threads": "每个任务的 CPU 线程",
  "ui.runner.threads_n": "{n} 线程",
  "ui.runner.max_jobs": "同时运行的任务",
  "ui.runner.jobs_n": "{n} 个",
  "ui.runner.engines": "计算引擎",
  "ui.runner.engines_none": "Runner 没有报告计算引擎。",
  "ui.runner.engines_summary": "计算引擎：已安装 {ok}/{total}",
  "ui.runner.engine_missing": "{name} 未安装。安装后可用；未安装时不会用近似结果顶替。",
  "ui.runner.copy_install": "复制安装命令",
  "ui.runner.network": "Runner 联网",
  "ui.runner.network_desc": "允许 Runner 访问在线数据源。每个项目仍需单独开启联网，每个新主机仍需批准。",
  "ui.runner.settings_offline": "Runner 未连接，设置没有更改。连接 Runner 后再试。",
  "ui.runner.settings_failed": "Runner 没有保存这项设置：{message}。显示的是 Runner 当前的设置。",
  "ui.runner.allow_remote": "允许把序列发送到第三方服务",
  "ui.runner.allow_remote_desc": "例如 ColabFold 的 MSA 服务器。关闭时，需要远程服务的工具会报告「不可用」。",
  "ui.pair.title": "配对本机 Runner",
  "ui.pair.body": "这个链接来自你电脑上的 tcmstudio serve（{host}）。连接后，工具可以在你的电脑上运行；数据不经过 science.impf.ai。",
  "ui.web.label": "联网",
  "ui.web.on": "联网",
  "ui.web.off": "不联网",
  "ui.web.on_tip": "本项目可以访问网络上的数据源（每个新主机仍需批准）",
  "ui.web.off_tip": "本项目不访问网络（默认）",
  "ui.web.on_toast": "已为本项目开启联网。访问新主机前仍会请求批准。",
  "ui.web.off_toast": "已为本项目关闭联网。",
  "ui.web.desc_project": "对「{name}」生效。访问新主机前仍会请求批准。",
  "ui.web.desc_default": "新项目的默认值。访问新主机前仍会请求批准。",
  "ui.web.desc_long": "开启后，模型可以调用在线数据源（文献、ChEMBL 等，需要本机 Runner）。默认关闭；每个新主机都会先请求批准。",
  "ui.web.default_label": "新项目默认联网",
  "ui.web.default_desc": "默认关闭。项目可以单独开启。",
  "ui.web.failed": "联网开关没有保存：{message}。显示的是浏览器里保存的状态。",
  "ui.net.offline": "设备已断网。浏览器里的工具、本机 Runner 和本地模型仍可使用；Tao-S1 和在线数据源要等网络恢复。",
  "ui.net.online": "网络已恢复。",
  "ui.offline.update": "新版本已就绪，重新载入即可使用。",
  "ui.offline.reload": "重新载入",
  "ui.browser.wasm": "WebAssembly：SIMD {simd}，多线程 {threads}",
  "ui.browser.threads_isolation": "需要跨源隔离",
  "ui.browser.webnn_none": "WebNN：此浏览器没有",
  "ui.browser.webnn_failed": "WebNN：无法创建上下文",
  "ui.browser.webnn_contexts": "WebNN：可创建上下文（{list}）。浏览器不报告实际由哪种处理器运行，NPU 未经证实；暂无工具使用 WebNN。",
  "ui.thread.label": "对话",
  "ui.thread.jump": "回到底部",
  "ui.thread.generating": "生成中",
  "ui.thread.running_tools": "正在运行 {n} 个工具",
  "ui.thread.waiting": "等待你的批准",
  "ui.thread.more_claims": "另有 {n} 条主张，在检查器中查看",
  "ui.thread.open_models": "打开模型设置",
  "ui.thread.error.model": "模型服务没有完成这次回答",
  "ui.thread.error.network": "网络中断",
  "ui.thread.error.runtime": "运行出错",
  "ui.thread.model_refused": "模型拒绝回答这次请求。",
  "ui.thread.fallback": "本条回答由 {model} 生成。",
  "ui.thread.served_by": "实际模型 {model}",
  "ui.thread.tool_count": "{n} 次工具调用",
  "ui.thread.usage": "输入 {input} tokens · 输出 {output} tokens",
  "ui.msg.edit": "编辑",
  "ui.msg.edit_note": "保存后会从这条消息开出一个新分支，原来的对话仍然保留（‹ › 切换）。",
  "ui.msg.edit_send": "保存并发送",
  "ui.msg.copy_md": "复制（Markdown）",
  "ui.msg.regenerate": "重新生成",
  "ui.branch.label": "分支 {i}/{n}",
  "ui.branch.prev": "上一个分支",
  "ui.branch.next": "下一个分支",
  "ui.turn.done": "回答完成",
  "ui.turn.done_tools": "回答完成，调用了 {n} 次工具",
  "ui.turn.failed_announce": "回答没有完成",
  "ui.turn.tool_refused": "{name} 已拒绝",
  "ui.turn.save_failed": "未能保存这一轮：{message}",
  "ui.run.thinking": "思考",
  "ui.run.thinking_note": "模型的思考不是证据",
  "ui.run.approval": "批准",
  "ui.run.gate": "发布门",
  "ui.run.answer": "回答",
  "ui.run.kind.model": "模型",
  "ui.run.kind.person": "你",
  "ui.run.kind.kernel": "内核判定",
  "ui.run.kind.tool": "工具",
  "ui.run.gov.native": "原生工具",
  "ui.run.gov.skill": "受治理 Skill",
  "ui.run.gov.connector": "数据源连接器",
  "ui.run.gov.clinic": "临床辨证",
  "ui.run.gov.tcmdb": "中医药数据枢纽",
  "ui.run.gov.study": "研究设计",
  "ui.run.gov.job": "任务",
  "ui.run.gov.system": "系统",
  "ui.run.live": "进行中",
  "ui.run.total": "共 {d}",
  "ui.run.tokens": "输入 {input} · 输出 {output} tokens",
  "ui.evidence.count": "{n} 条证据",
  "ui.evidence.view": "视图",
  "ui.evidence.list": "列表",
  "ui.evidence.table": "表格",
  "ui.evidence.note": "证据种类是类型，不是等级。质量四项分开列出，没有总分。",
  "ui.claims.filter": "筛选",
  "ui.claims.filter.all": "全部",
  "ui.claims.filter.allowed": "允许",
  "ui.claims.filter.refused": "拒绝",
  "ui.claims.filter.declaration": "需声明",
  "ui.claims.filter.extrapolation": "含外推",
  "ui.claims.note": "由内核规则判定，不是模型自评。被拒绝的主张保留在这里，附理由代码。",
  "ui.claims.none_for_filter": "没有符合这个筛选条件的主张。",
  "ui.files.loading": "载入中…",
  "ui.files.inputs": "输入",
  "ui.files.inputs_note": "本项目的文件保存在本浏览器（IndexedDB）。8 KB 以下的文本文件会随每条消息发送给所选模型；其余只有发送到本机 Runner 时才离开这台设备。",
  "ui.files.outputs": "输出",
  "ui.files.no_inputs": "本项目还没有文件。",
  "ui.files.no_outputs": "这一轮的工具没有声明输出文件。",
  "ui.files.loc_browser": "浏览器",
  "ui.files.loc_runner": "本机 Runner",
  "ui.files.digest_checked": "哈希已核验",
  "ui.files.digest_checked_tip": "Runner 按收集时记录的 sha256 核对了这个文件；这只说明文件未被改动，不代表结果已准予发布",
  "ui.files.loc_both": "浏览器 + 本机 Runner",
  "ui.files.job": "任务 {id} 的文件",
  "ui.files.preview": "预览",
  "ui.files.download": "下载",
  "ui.files.preview_failed": "无法预览：{message}",
  "ui.files.no_bytes": "没有文件内容",
  "ui.files.sandboxed": "报告在隔离框中显示，其中的脚本不会运行。",
  "ui.files.pdf": "PDF 请下载后查看。",
  "ui.files.truncated": "文件较大（{size}），只显示开头部分。",
  "ui.files.empty": "文件是空的。",
  "ui.files.table": "表格预览",
  "ui.files.rows": "显示前 {shown} 行，共 {total} 行",
  "ui.files.more_items": "另有 {n} 项",
  "ui.prov.pick": "选择一次工具运行",
  "ui.prov.run": "这次运行",
  "ui.prov.tool": "工具",
  "ui.prov.model": "模型",
  "ui.prov.where": "运行位置",
  "ui.prov.device": "设备",
  "ui.prov.runtime": "运行时",
  "ui.prov.versions": "版本",
  "ui.prov.started": "开始时间",
  "ui.prov.duration": "耗时",
  "ui.prov.attestation": "审计",
  "ui.prov.durable": "审计状态",
  "ui.prov.durable_yes": "已持久保存",
  "ui.prov.memory_only": "只在内存中（未持久保存）",
  "ui.prov.release": "发布状态",
  "ui.prov.sources": "数据源卡片 {n} 张",
  "ui.prov.artifact": "产物",
  "ui.prov.reproduce": "复现",
  "ui.prov.reproduce_note": "在装有 tcmstudio 的电脑上运行这条命令，会用同样的代码重新运行一次。输出文件的 sha256 可以逐一比对；整份结果的哈希含运行编号、时间和审计链位置，每次都不同。",
  "ui.prov.copy_cmd": "复制复现命令",
  "ui.prov.raw": "完整结果（JSON）",
  "ui.knowledge.title": "知识文件",
  "ui.knowledge.drop": "拖入文件，或点击选择",
  "ui.knowledge.privacy": "文件只保存在本浏览器，不会上传到 science.impf.ai。8 KB 以下的文本文件会随本项目的每条消息发送给所选模型（Tao-S1 经 science.impf.ai 中继转给模型服务）；标有「发送给模型」的文件就是这些。",
  "ui.knowledge.none": "还没有知识文件。8 KB 以下的文本文件会附在系统提示中、随每条消息发送给模型，其余只列出名称、大小和哈希。",
  "ui.knowledge.added": "已添加「{name}」并计算哈希",
  "ui.knowledge.uploaded": "上传",
  "ui.knowledge.from_tool": "工具生成",
  "ui.knowledge.big": "大于 200 MB",
  "ui.knowledge.send_runner": "发送到本机 Runner",
  "ui.knowledge.send_title": "发送到本机 Runner",
  "ui.knowledge.send_body": "把「{name}」复制到本机 Runner 的工作目录（127.0.0.1，你自己的电脑），供需要文件的工具使用。",
  "ui.knowledge.send": "发送",
  "ui.knowledge.uploading": "正在发送",
  "ui.knowledge.sent": "已发送「{name}」到本机 Runner",
  "ui.knowledge.hash_mismatch": "Runner 记录的哈希与浏览器计算的不一致，请重新发送。",
  "ui.knowledge.delete_title": "删除文件",
  "ui.knowledge.delete_body": "从本浏览器删除「{name}」。已发送到本机 Runner 的副本不受影响。",
  "ui.models.default_title": "默认模型",
  "ui.models.tao_sub": "TCMScience Studio 的研究助理",
  "ui.models.is_default": "默认",
  "ui.models.set_default": "设为默认",
  "ui.models.default_set": "已设为默认模型",
  "ui.models.check_relay": "检查中继",
  "ui.models.relay_error": "中继报告：{message}",
  "ui.models.limits": "调用限制",
  "ui.models.limits_unknown": "未知（中继未响应）",
  "ui.models.per_minute": "每分钟 {n} 次",
  "ui.models.per_day": "每天 {n} 次",
  "ui.models.tokens_per_day": "每天 {n} tokens",
  "ui.models.max_output": "单次最大输出",
  "ui.models.tokens": "{n} tokens",
  "ui.models.key": "密钥",
  "ui.models.no_key": "不需要",
  "ui.models.yours": "你的模型 API",
  "ui.models.key_note": "密钥只保存在本浏览器，不会发送到 science.impf.ai。清除浏览器数据会删除它。",
  "ui.models.key_note_short": "只保存在本浏览器，不会发送到 science.impf.ai。",
  "ui.models.remember": "记住密钥",
  "ui.models.remember_desc": "关闭后，密钥只保存在当前标签页，关闭即删除。",
  "ui.models.forget_keys": "删除所有密钥",
  "ui.models.forget_body": "从本浏览器删除你填写的全部 API 密钥。",
  "ui.models.forget": "删除",
  "ui.models.forgotten": "已删除所有密钥",
  "ui.models.configured": "已配置",
  "ui.models.configured_local": "已配置",
  "ui.models.no_key_set": "未填写密钥",
  "ui.models.not_set_local": "未配置",
  "ui.models.base_url": "接口地址",
  "ui.models.base_url_help": "留空则使用预设地址。",
  "ui.models.model": "模型",
  "ui.models.model_ph": "模型名称",
  "ui.models.test": "测试连接",
  "ui.models.testing": "正在测试：发送一次小请求，检查工具调用…",
  "ui.models.test_ok": "连接正常，支持工具调用",
  "ui.models.test_no_tools": "连接正常，但模型没有调用工具：它可能不支持工具调用，Studio 的工具将无法使用",
  "ui.models.test_failed": "连接失败",
  "ui.models.latency": "往返 {d}",
  "ui.models.first_token": "首个响应 {d}",
  "ui.models.via_runner": "经本机 Runner 转发",
  "ui.models.get_key": "获取密钥",
  "ui.models.reveal": "显示或隐藏密钥",
  "ui.models.custom": "自定义 API",
  "ui.models.no_custom": "还没有自定义接口。任何 OpenAI 兼容或 Anthropic 兼容的服务都可以添加。",
  "ui.models.add_openai": "添加 OpenAI 兼容接口",
  "ui.models.add_anthropic": "添加 Anthropic 兼容接口",
  "ui.models.format_openai": "OpenAI 兼容",
  "ui.models.format_anthropic": "Anthropic 兼容",
  "ui.models.label": "名称",
  "ui.models.max_tokens_param": "最大输出参数名",
  "ui.models.headers": "附加请求头（JSON）",
  "ui.models.extra_body": "附加请求体字段（JSON）",
  "ui.models.delete_custom": "删除这个接口",
  "ui.models.local": "本地模型",
  "ui.models.local_note": "浏览器访问 127.0.0.1 上的模型服务时，会先询问是否允许本站访问「本机上的应用」，请选择允许。服务本身还需要允许跨域（CORS）；也可以连接本机 Runner，由它转发。",
  "ui.models.detected_models": "{n} 个模型",
  "ui.models.not_answering": "没有响应",
  "ui.models.advanced": "高级",
  "ui.models.route": "模型调用路径",
  "ui.models.route_direct": "浏览器直连",
  "ui.models.route_runner": "经本机 Runner",
  "ui.models.route_help": "「自动」：能直连的服务直连；本地服务或不允许跨域的服务在 Runner 连接时经 Runner 转发。Tao-S1 始终直连中继。",
  "ui.models.thinking": "显示思考过程",
  "ui.models.thinking_desc": "模型支持时请求并显示思考过程（默认折叠）。思考不是证据。",
  "ui.models.max_tokens": "最大输出（tokens）",
  "ui.models.max_tokens_help": "每次模型调用的输出上限。Tao-S1 上限 8192。",
  "ui.models.max_steps": "每轮最多模型调用",
  "ui.models.max_steps_help": "一轮回答中模型最多被调用几次（含工具往返），默认 16。",
  "ui.models.temperature": "温度",
  "ui.models.temperature_default": "默认",
  "ui.models.temperature_help": "留空使用服务的默认值。",
  "ui.jobs.title": "任务",
  "ui.jobs.none": "本机 Runner 上还没有任务。",
  "ui.jobs.needs_runner": "连接本机 Runner 后，这里会列出它的任务（运行中、排队、已收集）。",
  "ui.job.connect_to_follow": "连接本机 Runner 后可查看这个任务的状态。",
  "ui.general.language": "语言",
  "ui.general.data": "数据与隐私",
  "ui.general.persistent": "数据保存在本浏览器（IndexedDB）",
  "ui.general.memory": "数据只保存在内存中",
  "ui.general.privacy": "项目、会话、文件和密钥都只在这台设备的这个浏览器里，不会同步到 science.impf.ai。但你发送的消息、工具结果和 8 KB 以下的项目文本文件会发给所选模型（Tao-S1 经 science.impf.ai 中继）。批准的数据库查询会经 science.impf.ai 网关转发至对应数据源。无痕窗口和「清除网站数据」会删除本地数据，需要保留时请导出。",
  "ui.general.counts": "{projects} 个项目 · {conversations} 个会话",
  "ui.general.export_label": "导出项目",
  "ui.general.export": "导出",
  "ui.general.import": "导入项目",
  "ui.general.import_help": "导入导出的 .json 文件，作为一个新项目；文件内容会按哈希逐一核对。",
  "ui.general.import_btn": "选择文件",
  "ui.general.imported": "已导入项目",
  "ui.general.clear": "清除本地数据",
  "ui.general.clear_help": "删除本浏览器中 Studio 的全部项目、会话、文件、密钥和缓存。",
  "ui.general.clear_btn": "清除全部",
  "ui.general.clear_title": "清除本地数据",
  "ui.general.clear_body": "这会删除本浏览器中 Studio 的全部数据，无法撤销。本机 Runner 上的文件不受影响。",
  "ui.general.onboarding": "首次引导",
  "ui.general.show_onboarding": "再看一次",
  "ui.settings.tab.models": "模型",
  "ui.settings.tab.compute": "计算",
  "ui.settings.tab.general": "通用",
  "ui.settings.tab.shortcuts": "快捷键",
  "ui.shortcuts.title": "快捷键",
  "ui.shortcuts.lede": "在 Mac 上用 ⌘ 和 ⌥，在 Windows 和 Linux 上用 Ctrl 和 Alt。",
  "ui.shortcuts.action": "操作",
  "ui.shortcuts.keys": "按键",
  "ui.shortcuts.note": "说明",
  "ui.shortcuts.or": "或",
  "ui.shortcuts.palette": "命令面板 / 搜索",
  "ui.shortcuts.palette_note": "项目、会话、命令、设置",
  "ui.shortcuts.new_chat": "新建会话",
  "ui.shortcuts.sidebar": "显示或隐藏侧栏",
  "ui.shortcuts.inspector": "显示或隐藏检查器",
  "ui.shortcuts.inspector_tab": "检查器第 1–5 页",
  "ui.shortcuts.focus": "聚焦输入框",
  "ui.shortcuts.focus_note": "「/」在不输入时可用",
  "ui.shortcuts.send": "发送",
  "ui.shortcuts.send_note": "中文输入法选字时不会发送",
  "ui.shortcuts.newline": "换行",
  "ui.shortcuts.stop": "停止生成",
  "ui.shortcuts.stop_note": "先关闭弹出层和抽屉",
  "ui.shortcuts.edit_last": "编辑上一条消息",
  "ui.shortcuts.edit_last_note": "输入框为空时",
  "ui.shortcuts.copy_last": "复制上一条回答",
  "ui.shortcuts.attach": "添加文件",
  "ui.shortcuts.sheet": "快捷键一览",
  "ui.palette.label": "命令面板",
  "ui.palette.placeholder": "搜索项目、会话、消息或命令…",
  "ui.palette.results": "结果",
  "ui.palette.none": "没有找到「{q}」",
  "ui.palette.move": "移动",
  "ui.palette.open": "打开",
  "ui.palette.group.recent": "最近会话",
  "ui.palette.group.projects": "项目",
  "ui.palette.group.conversations": "会话",
  "ui.palette.group.messages": "消息",
  "ui.palette.group.commands": "命令",
  "ui.palette.group.settings": "设置与页面",
  "ui.palette.toggle_lang": "切换语言",
  "ui.palette.toggle_theme": "切换外观",
  "ui.palette.copy_last": "复制上一条回答",
  "ui.palette.connect_runner": "连接本机 Runner",
  "ui.onb.title": "开始使用",
  "ui.onb.progress": "引导进度",
  "ui.onb.step.language": "语言",
  "ui.onb.step.model": "模型",
  "ui.onb.step.compute": "计算",
  "ui.onb.skip": "跳过",
  "ui.onb.back": "上一步",
  "ui.onb.next": "下一步",
  "ui.onb.start": "开始使用",
  "ui.onb.ready": "已就绪",
  "ui.onb.optional": "可选",
  "ui.onb.language_title": "界面语言",
  "ui.onb.language_text": "之后可以随时在右上角切换。中药名与方名在两种语言下都保留汉字。",
  "ui.onb.model_title": "模型：Tao-S1 已就绪",
  "ui.onb.model_more": "也可以接入你自己的模型 API（OpenAI、Anthropic、DeepSeek 等）或本地模型；密钥只保存在本浏览器。",
  "ui.onb.compute_title": "计算：在你自己的电脑上",
  "ui.onb.browser_text": "浏览器已就绪：TCMScience 的 Python 代码在这个页面里运行（Pyodide），无需安装。",
  "ui.onb.runner_text": "浏览器支持在线数据源与兼容的 GPU 工具；需要大文件、长任务或原生计算引擎时，在电脑上运行本机 Runner：",
  "ui.onb.runner_after": "它会打印一个配对链接，打开即可连接。数据留在你的电脑上。",
  "ui.catalog.search": "搜索工具",
  "ui.catalog.search_ph": "搜索：配伍、靶点、eGFR、reverse_complement…",
  "ui.catalog.lede": "{entries} 个工具与数据源，其中 {core} 个核心工具直接提供给模型，其余通过目录检索调用。",
  "ui.catalog.lede_empty": "工具目录",
  "ui.catalog.empty_title": "目录尚未加载",
  "ui.catalog.empty": "这个页面没有带上构建好的目录（runtime/catalog.json），也没有连接本机 Runner。连接 Runner 后，这里会列出它能运行的全部工具。",
  "ui.catalog.categories": "分类",
  "ui.catalog.all": "全部",
  "ui.catalog.count": "{n} 项",
  "ui.catalog.count_top": "最相关的 {n} 项",
  "ui.catalog.no_match": "没有匹配的工具。换个词试试（中文或英文都可以）。",
  "ui.catalog.detail": "工具详情",
  "ui.catalog.missing": "本机 Runner 缺少依赖：{deps}。未安装时不会用近似结果顶替。",
  "ui.catalog.core": "模型可直接调用：{names}",
  "ui.catalog.params": "参数",
  "ui.catalog.param": "参数",
  "ui.catalog.type": "类型",
  "ui.catalog.desc": "说明",
  "ui.catalog.required": "必填",
  "ui.catalog.default": "默认",
  "ui.catalog.no_params": "没有参数。",
  "ui.catalog.example": "示例",
  "ui.catalog.skill": "受治理 Skill",
  "ui.catalog.version": "版本",
  "ui.catalog.pinned": "已固定版本",
  "ui.catalog.claim_kinds": "可产生的主张类型",
  "ui.catalog.forbidden": "禁止的主张类型",
  "ui.catalog.max_tier": "最高证据等级",
  "ui.catalog.hosts": "访问的主机",
  "ui.catalog.no_network": "不联网",
  "ui.catalog.content_hash": "内容哈希",
  "ui.catalog.try": "在新会话中试用",
  "ui.catalog.try_prompt": "请用「{title}」（{id}）",
  "ui.catalog.badge.browser": "浏览器",
  "ui.catalog.badge.runner": "本机",
  "ui.catalog.badge.network": "联网",
  "ui.catalog.badge.confirm": "需确认",
  "ui.catalog.badge.job": "任务",
  "ui.catalog.badge.missing": "缺少依赖",
  "ui.catalog.badge.now": "现在可运行（{where}）",
  "ui.catalog.badge.not_now": "现在不可运行",
  "ui.catalog.kind.native": "原生工具",
  "ui.catalog.kind.skill": "受治理 Skill",
  "ui.catalog.kind.connector": "数据源连接器",
  "ui.catalog.kind.clinic": "临床辨证",
  "ui.catalog.kind.tcmdb": "数据枢纽",
  "ui.catalog.kind.study": "研究设计",
  "ui.catalog.kind.job": "任务",
  "ui.catalog.kind.system": "系统",
  "ui.about.title": "TCMScience Studio",
  "ui.about.lede": "TCMScience 的研究工作台：一个受治理的科学智能体。它调用 TCMScience 的工具和 Skill，并把每次运行在哪里、用了什么证据、证据能支撑哪类主张，写在结果旁边。",
  "ui.about.what": "它做什么",
  "ui.about.what.1": "对话中调用 150 个原生工具、受治理的 Skill、临床辨证、中医药数据枢纽和在线数据源。",
  "ui.about.what.2": "每条主张都由内核按证据种类判定：允许、拒绝或需要声明外推，并给出理由代码。",
  "ui.about.what.3": "每次工具运行都记录运行位置、设备、耗时、输入与输出哈希和复合版本，可以复现。",
  "ui.about.what.4": "拒绝是结果：被拒绝的主张和调用会显示出来，不会被隐藏。",
  "ui.about.where": "计算和数据在哪里",
  "ui.about.where.1": "工具在浏览器中运行（Pyodide WASM CPU，兼容的序列统计可用 WebGPU），或在电脑上的本机 Runner 中运行。",
  "ui.about.where.2": "science.impf.ai 提供页面、Tao-S1 中继和受限数据库网关，不保存会话。批准联网后，数据库请求会经网关转发到对应数据源。",
  "ui.about.where.3": "联网、发送数据到第三方服务和启动任务之前，都会先请求你的批准。",
  "ui.about.where.4": "你自己的模型 API 密钥只保存在本浏览器，请求直接发往你选择的服务（或经本机 Runner 转发）。",
  "ui.about.not": "它不声称什么",
  "ui.about.not.1": "不提供诊断或处方。临床辨证给出的是供执业医师审阅的草稿，签发是人的行为。",
  "ui.about.not.2": "经典记载不等于临床证据；无记录不等于安全。",
  "ui.about.not.3": "网络药理学、对接和靶点预测是计算预测，最多支撑机制假说，不等于实测。",
  "ui.about.not.4": "「已准予发布」只说明六项检查都已满足，不说明结论正确。",
  "ui.about.not.5": "模型的思考与措辞不是证据；证据能支撑什么，由内核规则判定。",
  "ui.about.privacy": "隐私",
  "ui.about.privacy_text": "没有账号，也没有同步。项目、会话和文件只在这台设备的浏览器里；需要保留或迁移时，请在「设置 → 通用」中导出。发给模型的内容除外：你的消息、工具结果和 8 KB 以下的项目文本文件会发给所选模型（Tao-S1 经 science.impf.ai 中继转给模型服务）。批准的数据库请求与响应也会经过本站网关，但不保存。",
  "ui.about.links": "链接",
  "ui.about.link.project": "项目主页",
  "ui.about.link.arena": "Arena：受治理与不受治理的对照",
  "ui.about.link.github": "GitHub 源代码",
  "ui.about.versions": "版本",
  "ui.about.catalog": "工具目录",
  "ui.about.catalog_n": "{core} 个核心工具 · {entries} 个条目",
  "ui.about.motto": "让语言模型推理，但不让它定义实验室的法则。",
  // review fixes (web-ui)
  "ui.runner.paired": "已连接本机 Runner（{host}）",
  "ui.composer.store_failed": "附件没有存下，消息未发送：{message}",
  "ui.composer.send_failed": "消息未发送：{message}",
  "ui.composer.busy_elsewhere": "「{title}」中的回答还在生成：一次只生成一个回答。等它完成，或先停止它。",
  "ui.composer.stop_other": "停止那个回答",
  "ui.composer.busy_tip": "另一个会话的回答还在生成",
  "ui.knowledge.to_model": "发送给模型",
  "ui.knowledge.to_model_tip": "8 KB 以下的文本文件：它的全文附在系统提示中，随本项目的每条消息发送给所选模型。",
  "ui.code.UNPINNED": "候选 Skill：没有锁定文件固定它的版本，运行会记录，但结果永不发布",
  "ui.kernel.original": "英文原文",
  "ui.kernel.original_tip": "内核的原始记录，按原文显示，不做翻译",
  "ui.claim.basis_k": "依据：",
  "ui.claim.falsify_short_k": "可被推翻：",
  "ui.release.unmet.schema_valid": "结构无效",
  "ui.release.unmet.evidence_verified": "引文未核验",
  "ui.release.unmet.outputs_verified": "输出未核验",
  "ui.release.unmet.execution_declared": "未声明执行",
  "ui.release.unmet.execution_attested": "执行未证明",
  "ui.release.unmet.release_authorized": "未准予发布",
  "ui.release.unmet_k": "未满足：",
  "ui.release.count": "发布状态 {passed}/{total}",
  "ui.artifact.chain_head": "Runner 审计链头（不是产物的证明）",
  "ui.artifact.candidate": "候选 · 未锁定，不会发布",
  "ui.artifact.candidate_tip": "这个 Skill 没有在锁定文件中固定版本：运行会记录，但结果不会被准予发布。",
  "ui.artifact.candidate_short": "候选",
  "ui.artifact.status_k": "产物状态",
  "ui.artifact.status_v": "{status}（工作流状态，未经人工验证）",
  "ui.evidence.select_row": "在列表中选中证据 {id}",
  "ui.tool.declined": "未批准 · 未运行",
  "ui.tool.clinic_draft": "草案 · 待执业医师审核签署",
  "ui.tool.interrupted": "已中断",
  "ui.tool.interrupted_line": "页面在运行期间关闭或重新载入：这次调用是否完成，这里无法得知。",
  "ui.tool.kernel_refusals": "内核的拒绝 {n} 条",
  "ui.thread.interrupted_title": "这一轮被中断了",
  "ui.thread.interrupted": "页面在生成时重新载入或关闭。已经保存的文字和工具结果保留在下方；没有结果的调用不知道是否完成。可以重新生成。",
  "ui.msg.you": "你说",
  "ui.msg.assistant": "{model} 的回答",
  "ui.model.relay_checking": "正在检查中继",
  "ui.onb.model_title.checking": "模型：正在检查 Tao-S1",
  "ui.onb.model_title.ready": "模型：Tao-S1 已就绪",
  "ui.onb.model_title.down": "模型：先接入一个模型",
  "ui.onb.model_down": "Tao-S1 的中继现在不可用。接入你自己的模型 API（OpenAI、Anthropic、DeepSeek 等）或本地模型后即可开始；密钥只保存在本浏览器。",
  "ui.inspector.empty_turn.run": "此回答没有运行记录；整个会话有 {n} 步",
  "ui.inspector.empty_turn.evidence": "此回答没有证据；整个会话有 {n} 条",
  "ui.inspector.empty_turn.claims": "此回答没有主张；整个会话有 {n} 条",
  "ui.inspector.empty_turn.provenance": "此回答没有工具运行；整个会话有 {n} 次",
  "ui.inspector.show_all": "查看整个会话",
  "ui.prov.refusals": "内核的拒绝 {n} 条",
  "ui.prov.pinned": "版本锁定",
};

// English counts: "1 tool call", "2 tool calls" (t() calls a function value with its vars)
const plural = (one, many) => ({ n }) => (Number(n) === 1 ? one : many).replace("{n}", String(n));

export const EN = {
  "ui.action.cancel": "Cancel",
  "ui.action.close": "Close",
  "ui.action.confirm": "OK",
  "ui.action.copy": "Copy",
  "ui.action.save": "Save",
  "ui.action.open_inspector": "Open in inspector",
  "ui.common.yes": "Yes",
  "ui.common.no": "No",
  "ui.toast.copied": "Copied",
  "ui.toast.copy_failed": "Could not copy: the browser blocked clipboard access",

  "ui.hash.aria": "{visible} (full value {value}). Copy hash",
  "ui.hash.copied": "Full hash copied",
  "ui.hash.none": "No hash",

  "ui.family.predicted_tip": "This is a computational prediction, not a measurement. It licenses a mechanism hypothesis at most.",
  "ui.family.unknown": "Unknown kind",
  "ui.ladder.licenses": "licenses this claim kind",
  "ui.ladder.weakest": "this claim's weakest evidence",
  "ui.ladder.no_weakest": "Claim kind: {kind} — no evidence tier to judge",

  "ui.claim.kind_tip": "Claim kind: it decides which evidence can license the claim",
  "ui.claim.supports": "Rests on",
  "ui.claim.no_support": "Cites no evidence",
  "ui.claim.remedy": "Remedy",
  "ui.claim.weakest": "Weakest link",
  "ui.claim.weakest_short": "Weakest: {tier}",
  "ui.claim.caveats": plural("{n} caveat", "{n} caveats"),
  "ui.claim.caveats_short": plural("{n} caveat", "{n} caveats"),
  "ui.claim.extrapolations": plural("{n} extrapolation not validated by evidence", "{n} extrapolations not validated by evidence"),
  "ui.claim.extrap_short": plural("{n} extrapolation", "{n} extrapolations"),
  "ui.claim.falsified_by": "What would falsify it",
  "ui.claim.falsified_by_none": "Not stated",
  "ui.claim.falsify_short": "Falsified by: {text}",
  "ui.claim.confidence": "Confidence",
  "ui.claim.basis": "basis: {basis}",
  "ui.claim.no_basis": "no basis stated",

  "ui.release.met": "met",
  "ui.release.unmet": "not met",
  "ui.release.details": "The six release states",
  "ui.artifact.untitled": "Artifact",
  "ui.artifact.status_tip": "Artifact status: the workflow state the Skill reports, not human-validated; whether it is released is the kernel's verdict.",
  "ui.artifact.output_verified": "Verified",
  "ui.artifact.limitations": plural("{n} limitation", "{n} limitations"),
  "ui.artifact.no_limitations": "No limitations stated: by contract such an artifact is invalid (ART110)",
  "ui.artifact.more_limits": "{n} more in the inspector",
  "ui.artifact.warnings": "{n} warnings",
  "ui.artifact.violations": "{n} checks not passed",
  "ui.artifact.assumptions": "Assumptions",
  "ui.artifact.none": "none",
  "ui.artifact.not_attested": "not attested by the audit chain",
  "ui.cv.title": "Composite version",
  "ui.cv.runtime": "Runtime",
  "ui.cv.skill": "Skill",
  "ui.cv.source": "Source",
  "ui.cv.benchmark": "Benchmark",
  "ui.cv.unversioned": "Unversioned",

  "ui.quality.risk_of_bias": "Risk of bias",
  "ui.quality.directness": "Directness",
  "ui.quality.precision": "Precision",
  "ui.quality.consistency": "Consistency",
  "ui.quality.not_assessed": "Not assessed",
  "ui.quality.none": "None of the four quality dimensions was assessed",
  "ui.evidence.quote_verified": "Quote verified",
  "ui.evidence.quote_unverified": "Quote not verified",
  "ui.evidence.quote_verified_short": "Verified",
  "ui.evidence.quote_unverified_short": "Not verified",
  "ui.evidence.conflicts": "Conflicts with {n}",
  "ui.evidence.source_tip": "Source card",
  "ui.evidence.source_missing": "card not in the artifact",
  "ui.evidence.table_label": "Evidence table",
  "ui.evidence.col.design": "Kind · design",
  "ui.evidence.col.citation": "Citation",
  "ui.evidence.col.quote": "Quote",
  "ui.evidence.col.retraction": "Retraction",
  "ui.evidence.col.hash": "Content hash",
  "ui.source.licence": "Licence",
  "ui.source.unlicensed": "No licence declared",
  "ui.source.kind": "Kind",
  "ui.source.access": "Access",
  "ui.source.snapshot": "Snapshot",
  "ui.source.unpinned": "Not pinned to a snapshot",
  "ui.source.offline": "Offline",
  "ui.source.limits": "Known limits",
  "ui.cite.aria": "Evidence {id}: {label}",
  "ui.cite.unknown": "{id}: no tool result in this turn has this citation",

  "ui.think.title": "Thinking",
  "ui.think.live": "Thinking · {s} s",
  "ui.think.done": "Thought · {d}",
  "ui.think.note": "The model's thinking is not evidence and is never cited.",

  "ui.where.browser": "Browser",
  "ui.where.runner": "Local runner",
  "ui.where.relay": "Relay",
  "ui.where.browser_short": " in the browser",
  "ui.where.runner_short": " on this computer",
  "ui.where.decided_in_page": "decided by the page; the tool did not run",
  "ui.where.not_run": "Not run",
  "ui.release.more": "{n} more in the inspector",

  "ui.tool.running_at": "Running {name}{place} · {device}",
  "ui.tool.preparing": "Preparing a call to {name}…",
  "ui.tool.waiting_approval": "Not run yet",
  "ui.tool.claims_refused": plural("{n} claim refused", "{n} claims refused"),
  "ui.tool.args": "Arguments",
  "ui.tool.args_json": "Full arguments (JSON)",
  "ui.tool.result": "Result (first lines)",
  "ui.tool.more_lines": plural("{n} more line; the full result is in the inspector", "{n} more lines; the full result is in the inspector"),
  "ui.tool.input": "in",
  "ui.tool.output": "out",
  "ui.tool.not_durable": "audit state kept in memory only",

  "ui.perm.title": "Needs your approval",
  "ui.perm.title_decided": "Approval",
  "ui.perm.network": "It will reach these hosts on the network:",
  "ui.perm.no_hosts": "(no hosts declared)",
  "ui.perm.job": "It will start a job on the local runner: {what}. The job runs on your computer and can be cancelled; its outputs are not a result until it is collected and verified.",
  "ui.perm.confirm": "This action needs confirmation: {what}.",
  "ui.perm.remote_upload": "It will send data to a third-party service; the data leaves your computer:",
  "ui.perm.first_runner": "This is the first tool run on the local runner for this project. The runner listens on 127.0.0.1; your data does not leave your computer.",
  "ui.perm.once": "Allow once",
  "ui.perm.project": "Allow for this project",
  "ui.perm.deny": "Deny",
  "ui.perm.decided.once": "Allowed once",
  "ui.perm.decided.project": "Allowed for this project",
  "ui.perm.decided.deny": "Not approved · not run",

  "ui.job.step.submitted": "Submitted",
  "ui.job.step.running": "Running",
  "ui.job.step.collected": "Collected and verified",
  "ui.job.progress": "Job progress",
  "ui.job.pending_note": "Until the job is collected and verified, nothing it produced is shown as a result.",
  "ui.job.no_result": "This job has no result.",
  "ui.job.failed": "The job did not finish.",
  "ui.job.cancel": "Cancel job",
  "ui.job.logs": plural("Log · {n} line", "Log · {n} lines"),
  "ui.job.kind.pipeline.rnaseq": "RNA-seq pipeline",
  "ui.job.kind.pipeline.scrna": "Single-cell pipeline",
  "ui.job.kind.pipeline.fold": "Protein structure prediction",
  "ui.job.kind.pipeline.dock": "Molecular docking",
  "ui.job.kind.pipeline.admet": "ADMET prediction",
  "ui.job.kind.research.run": "Network pharmacology research loop",
  "ui.job.kind.skill.run": "Governed skill run",
  "ui.job.kind.tcmdb.fetch": "Download a TCM dataset",
  "ui.job.kind.tcmdb.build": "Build the local database",
  "ui.theme.system": "System",
  "ui.theme.light": "Light",
  "ui.theme.dark": "Dark",

  "ui.gallery.title": "Component gallery · design QA",
  "ui.gallery.workspace": "Workspace",
  "ui.gallery.workspace_lede": "The conversation, tool cards, claim and artifact cards, the branch switcher (‹1/2›) and the inspector, rendered by the app's own modules; the tool results are the real-run envelopes above.",
  "ui.gallery.composer": "Composer",
  "ui.gallery.panels": "Compute and model panels",
  "ui.gallery.project": "Project overview",
  "ui.gallery.primitives": "Primitives",
  "ui.gallery.governance": "Governance language",
  "ui.gallery.claims": "Claims",
  "ui.gallery.artifacts": "Artifacts and release",
  "ui.gallery.evidence": "Evidence",
  "ui.gallery.run": "Run transparency",
  "ui.gallery.jobs": "Jobs",
  "ui.gallery.tokens_lede": "Design tokens (DESIGN §5). Every colour is contrast-checked in light and dark.",
  "ui.gallery.kicker": "Governance layer",
  "ui.gallery.open_menu": "Menu",
  "ui.gallery.open_popover": "Popover",
  "ui.gallery.open_dialog": "Dialog",
  "ui.gallery.claims_lede": "These claims were judged by the kernel (validate_artifact): an efficacy claim that rests on a cell study (CLM005), a docking prediction stated as fact (CLM004), and a mechanism hypothesis that is allowed, with caveats.",

  "ui.action.create": "Create",
  "ui.action.delete": "Delete",
  "ui.action.later": "Later",
  "ui.action.rename": "Rename",
  "ui.action.retry": "Retry",
  "ui.action.undo": "Undo",
  "ui.skip.composer": "Skip to the message box",
  "ui.skip.main": "Skip to the main content",
  "ui.toasts.label": "Notifications",
  "ui.toast.code_copied": "Code copied",
  "ui.code.wrap": "Wrap",
  "ui.project.approval.runner": "Run tools on the local runner",
  "ui.project.approval.network": "network",
  "ui.project.approval.remote": "send data to a third party",
  "ui.project.approval.run": "run (a job or an action that asks first)",
  "ui.skip.thread": "Skip to the conversation",
  "ui.boot.loading": "Loading…",
  "ui.storage.memory": "This browser does not let the site use IndexedDB (a private window, for example). Projects and conversations are kept in memory only and are gone when the page closes.",
  "ui.toast.answer_copied": "Answer copied (Markdown, with citations)",
  "ui.nav.new_chat": "New conversation",
  "ui.nav.search": "Search",
  "ui.nav.settings": "Settings",
  "ui.nav.about": "About",
  "ui.nav.catalog": "Tool catalog",
  "ui.notfound.title": "No such page",
  "ui.notfound.body": "The address is wrong, or the data it points to is kept in a browser on another device.",
  "ui.notfound.home": "Back to start",
  "ui.sidebar.label": "Projects and conversations",
  "ui.sidebar.toggle": "Toggle sidebar",
  "ui.sidebar.more": "More",
  "ui.sidebar.projects": "Projects",
  "ui.sidebar.recent": "Recent",
  "ui.sidebar.conversations": "In this project",
  "ui.sidebar.conversations_in": "Conversations in {name}",
  "ui.sidebar.no_projects": "No projects yet. One is created when you send your first message.",
  "ui.sidebar.no_conversations": "No conversations yet.",
  "ui.sidebar.archived": "{n} archived",
  "ui.sidebar.group.pinned": "Pinned",
  "ui.sidebar.group.today": "Today",
  "ui.sidebar.group.yesterday": "Yesterday",
  "ui.sidebar.group.week": "Previous 7 days",
  "ui.sidebar.group.older": "Older",
  "ui.topbar.breadcrumb": "You are here",
  "ui.topbar.project_tip": "Project overview",
  "ui.topbar.rename_tip": "Rename conversation",
  "ui.lang.switch": "Switch language (中文 / English)",
  "ui.theme.title": "Appearance",
  "ui.theme.switch": "Appearance: {theme}",
  "ui.inspector.label": "Inspector",
  "ui.inspector.toggle": "Inspector",
  "ui.inspector.tabs": "Inspector tabs",
  "ui.inspector.close": "Close inspector",
  "ui.inspector.resize": "Resize the inspector",
  "ui.inspector.expand": "Expand to full height",
  "ui.inspector.collapse": "Collapse",
  "ui.inspector.scope": "Scope",
  "ui.inspector.scope_turn": "This answer",
  "ui.inspector.scope_all": "Whole conversation",
  "ui.inspector.goto_turn": "Show in the conversation",
  "ui.inspector.tab.run": "Run",
  "ui.inspector.tab.evidence": "Evidence",
  "ui.inspector.tab.claims": "Claims",
  "ui.inspector.tab.files": "Files",
  "ui.inspector.tab.provenance": "Provenance",
  "ui.inspector.empty.run_title": "Nothing has run yet",
  "ui.inspector.empty.run": "When the model calls tools, each step is listed here in order: thinking, tool runs, your approvals, release-gate checks.",
  "ui.inspector.empty.evidence_title": "No evidence yet",
  "ui.inspector.empty.evidence": "After a tool runs, each evidence item is listed here with its kind and source snapshot.",
  "ui.inspector.empty.claims_title": "No claims yet",
  "ui.inspector.empty.claims": "When a tool returns claims, each one is listed here with the kernel's verdict and reason codes. Refused claims stay listed.",
  "ui.inspector.empty.prov_title": "No run to trace yet",
  "ui.inspector.empty.prov": "After a tool runs, its composite version, source snapshots, audit head and a reproduce command appear here.",
  "ui.conv.untitled": "Untitled conversation",
  "ui.conv.rename": "Rename conversation",
  "ui.conv.menu": "Actions for “{name}”",
  "ui.conv.pin": "Pin",
  "ui.conv.unpin": "Unpin",
  "ui.conv.delete_title": "Delete conversation",
  "ui.conv.delete_body": "Delete “{name}” with all its messages and tool results. Only this browser's copy is deleted; this cannot be undone.",
  "ui.conv.missing": "This conversation was not found: it may have been deleted, or it is kept in a browser on another device.",
  "ui.project.default_name": "My research",
  "ui.project.kicker": "Project",
  "ui.project.empty_title": "New project",
  "ui.project.empty_body": "Write a research question, or start from an example below. Each example shows one refusal by the kernel.",
  "ui.project.new": "New project",
  "ui.project.name": "Project name",
  "ui.project.name_ph": "e.g. Gegen Qinlian decoction · network pharmacology review",
  "ui.project.rename": "Rename project",
  "ui.project.menu": "Actions for “{name}”",
  "ui.project.edit_desc": "Edit description",
  "ui.project.export": "Export project",
  "ui.project.exported": "Project exported (JSON, with files and hashes)",
  "ui.project.archive": "Archive",
  "ui.project.unarchive": "Unarchive",
  "ui.project.archived": "Archived “{name}”",
  "ui.project.delete_title": "Delete project “{name}”",
  "ui.project.delete_body": "Delete all conversations, messages and knowledge files of this project. Only this browser's copy is deleted; this cannot be undone. Export it first if you want to keep it.",
  "ui.project.missing": "This project was not found: it may have been deleted, or it is kept in a browser on another device.",
  "ui.project.save_failed": "The project setting was not saved: {message}. What is shown is what this browser holds.",
  "ui.project.conversations": "Conversations",
  "ui.project.instructions": "Instructions",
  "ui.project.instructions_ph": "e.g. Separate records, predictions and measurements; cite the Chinese Pharmacopoeia first.",
  "ui.project.instructions_help": "Added after the system prompt in every conversation. It shapes how the model writes; it cannot loosen the kernel's verdicts.",
  "ui.project.saving": "Saving…",
  "ui.project.saved": "Saved",
  "ui.project.defaults": "Defaults",
  "ui.project.default_model": "Default model",
  "ui.project.default_model_help": "Used by new conversations in this project; each conversation can still switch beside the message box.",
  "ui.project.default_compute": "Compute target",
  "ui.project.default_compute_help": "Where this project's tools run.",
  "ui.project.follow_global": "Follow the global setting",
  "ui.project.approvals": "Approved for this project",
  "ui.project.approvals_help": "These are no longer asked each time in this project. Revoke one and the next run asks again.",
  "ui.project.revoke": "Revoke",
  "ui.project.recent_claims": "Recent claims",
  "ui.project.no_claims": "This project has produced no claims yet.",
  "ui.examples.label": "Examples",
  "ui.examples.runner_chip": "Needs the local runner",
  "ui.examples.needs_runner": "This example needs the local runner.",
  "ui.examples.normalize.prompt": "Normalize: 姜, 白芍",
  "ui.examples.normalize.shows": "Ambiguity is kept: 姜 may be fresh (生姜) or dried (干姜) ginger; nothing is chosen for you.",
  "ui.examples.network.prompt": "What the corpus records for 桂枝汤: its herbs and any targets",
  "ui.examples.network.shows": "The seed corpus records no targets: the herbs and recorded indications are listed, no network is built and no claim is made; measured targets need the runner's network-pharmacology job.",
  "ui.examples.safety.prompt": "What is recorded about using 甘草 with 甘遂?",
  "ui.examples.safety.shows": "An 十八反 incompatibility, reported as a record, not as a clinical safety signal.",
  "ui.examples.evidence.prompt": "What evidence exists for 附子? Group it by evidence kind",
  "ui.examples.evidence.shows": "The evidence is reported with its kind, not adjudicated.",
  "ui.examples.enrichment.prompt": "Re-check the enrichment of 葛根芩连汤 against the proteins actually assayed",
  "ui.examples.enrichment.shows": "Reproduces the project page's case: change the background set and the enrichment changes with it.",
  "ui.composer.label": "Message",
  "ui.composer.placeholder": "Ask, or describe the analysis…",
  "ui.composer.placeholder_hero": "Write a research question…",
  "ui.composer.placeholder_streaming": "Answering… you can write the next message",
  "ui.composer.attach": "Attach files",
  "ui.composer.attachments": "Attachments",
  "ui.composer.send": "Send",
  "ui.composer.stop": "Stop generating",
  "ui.composer.stop_tip": "Stop generating (Esc)",
  "ui.composer.options": "Model and compute",
  "ui.composer.foot": "The model reasons; the kernel decides which claims the evidence licenses.",
  "ui.composer.drop": "Drop to attach",
  "ui.composer.drop_note": "Files are stored only in this browser and are not uploaded to science.impf.ai. Text files under 8 KB, however, are sent to the selected model with every message in this project (for Tao-S1, through the science.impf.ai relay to the model service); other files leave this device only when you send them to the local runner.",
  "ui.composer.hashing": "Hashing {p}%",
  "ui.composer.hash_failed": "Could not read the file",
  "ui.composer.wait_hash": "Wait until the attachments are hashed.",
  "ui.composer.remove": "Remove {name}",
  "ui.composer.big_file": "Over 200 MB: better processed by the local runner.",
  "ui.model.title": "Model",
  "ui.model.chip_tip": "Choose the model",
  "ui.model.default": "Default",
  "ui.model.tao_sub": "Through the science.impf.ai relay · no key",
  "ui.model.yours": "Your APIs",
  "ui.model.local": "Local models",
  "ui.model.detected": "{label} · detected",
  "ui.model.detect": "Detect local models",
  "ui.model.detect_needs_runner": "Detecting local models needs the local runner.",
  "ui.model.detected_n": plural("Found {n} local model server", "Found {n} local model servers"),
  "ui.model.detected_none": "No local model server is running.",
  "ui.model.manage": "Add or manage models",
  "ui.model.this_conv": "This conversation only",
  "ui.model.this_new": "New conversation only",
  "ui.model.relay_ok": "Relay available",
  "ui.model.relay_down": "Relay unavailable",
  "ui.compute.title": "Compute",
  "ui.compute.chip_tip": "Where computation runs",
  "ui.compute.chip.browser": "Browser",
  "ui.compute.chip.runner": "This computer · {device}",
  "ui.compute.chip.runner_off": "This computer (not connected)",
  "ui.compute.target": "Compute target",
  "ui.compute.auto": "Auto",
  "ui.compute.auto_tip": "On the local runner while it is connected; otherwise, what can run in the browser runs there.",
  "ui.compute.browser": "Browser",
  "ui.compute.runner": "Local runner",
  "ui.compute.target_help.auto": "While the local runner is connected, tools run on it (native Python, the project's durable audit chain, your devices); otherwise what can run in the browser runs there, and network, heavy dependencies, GPU and long jobs need the runner.",
  "ui.compute.target_help.browser": "Browser only; a tool that runs only on the runner reports “unavailable”, and nothing approximate is substituted.",
  "ui.compute.target_help.runner": "Local runner only; while it is not connected, tools report “unavailable”.",
  "ui.compute.project_override": "(project setting of “{name}”)",
  "ui.compute.browser_runtime": "Browser",
  "ui.compute.browser_sub": "Pyodide · Web Worker",
  "ui.compute.runner_runtime": "Local runner",
  "ui.compute.mobile": "The local runner runs on a computer. On a phone, tools run in the browser.",
  "ui.compute.more": "More compute settings",
  "ui.browser.status.idle": "Not loaded",
  "ui.browser.status.loading": "Loading",
  "ui.browser.status.connecting": "Loading",
  "ui.browser.status.ready": "Ready",
  "ui.browser.status.error": "Error",
  "ui.browser.status.offline": "Unavailable",
  "ui.browser.loading": "Loading the Python runtime",
  "ui.browser.idle_note": "The Python runtime (about 9 MB) downloads on the first tool run, then comes from the browser cache.",
  "ui.browser.offline_note": "This page was built without the browser runtime. Tools still run once the local runner is connected.",
  "ui.browser.cpu_note": "Python tools run on the CPU (single thread, WebAssembly).",
  "ui.browser.cores": "{cores} logical cores{memory}",
  "ui.browser.memory": " · about {gb} GB memory",
  "ui.browser.webgpu_none": "This browser has no WebGPU.",
  "ui.browser.webgpu_no_adapter": "This browser supports WebGPU, but no GPU adapter is available (CPU will be used).",
  "ui.browser.webgpu_software": "The WebGPU adapter is a software emulator ({name}), not a GPU.",
  "ui.browser.webgpu_hw": "WebGPU: {name}. Compatible sequence statistics can use the GPU with automatic CPU fallback.",
  "ui.browser.acceleration": "Browser acceleration",
  "ui.browser.acceleration_auto": "Auto: the fastest verified backend (WebGPU for compatible tools, then the CPU kernels); the original Python otherwise",
  "ui.browser.acceleration_cpu": "CPU only: the CPU kernels (JavaScript) and Python; no GPU",
  "ui.browser.acceleration_reference": "Python reference only: the original implementation for every tool (to check results)",
  "ui.browser.acceleration_help": "Computation starts only when you run a tool. Sequence distance matrices, Hamming distance and GC content can use the GPU; sequence alignment, edit distance and those counts also have CPU kernels. Results are byte-identical to the original Python, every result is checked in Python, and the receipt says what computed it. Other Python tools run on the WebAssembly CPU.",
  "ui.browser.isolated": "Cross-origin isolated: a running Python call can be interrupted.",
  "ui.browser.not_isolated": "Not cross-origin isolated: a running Python call stops only by restarting the worker.",
  "ui.browser.preload": "Preload",
  "ui.runner.status.idle": "Not connected",
  "ui.runner.status.offline": "Not connected",
  "ui.runner.status.connecting": "Connecting",
  "ui.runner.status.ready": "Connected",
  "ui.runner.status.error": "Connection failed",
  "ui.runner.unavailable": "The runtime modules are not available.",
  "ui.runner.connected": "Local runner connected",
  "ui.runner.connect": "Connect",
  "ui.runner.connecting": "Connecting…",
  "ui.runner.disconnect": "Disconnect",
  "ui.runner.not_connected": "The local runner is not connected. In-browser compute still works; large files and GPU jobs need the runner.",
  "ui.runner.how": "Run in a terminal on your computer",
  "ui.runner.how_help": "It prints a pairing link; open it to pair automatically. Or enter the address and token below.",
  "ui.runner.enter_token": "Enter address and token",
  "ui.runner.url": "Runner address",
  "ui.runner.token": "Pairing token",
  "ui.runner.token_help": "The token printed in the terminal. It stays in this browser.",
  "ui.runner.cores": plural("{n} core", "{n} cores"),
  "ui.runner.cpu_unknown": "CPU details unavailable",
  "ui.runner.memory": "{gb} GB memory",
  "ui.runner.device": "Device",
  "ui.runner.device_auto": "Choose automatically",
  "ui.runner.threads": "CPU threads per job",
  "ui.runner.threads_n": plural("{n} thread", "{n} threads"),
  "ui.runner.max_jobs": "Jobs at once",
  "ui.runner.jobs_n": "{n}",
  "ui.runner.engines": "Engines",
  "ui.runner.engines_none": "The runner reported no engines.",
  "ui.runner.engines_summary": "Engines installed: {ok}/{total}",
  "ui.runner.engine_missing": "{name} is not installed. It works once installed; nothing approximate is substituted.",
  "ui.runner.copy_install": "Copy install command",
  "ui.runner.network": "Runner network access",
  "ui.runner.network_desc": "Lets the runner reach online data sources. Each project still turns web access on itself, and each new host is still approved.",
  "ui.runner.settings_offline": "The runner is not connected, so the setting was not changed. Connect the runner and try again.",
  "ui.runner.settings_failed": "The runner did not save this setting: {message}. What is shown is what the runner holds now.",
  "ui.runner.allow_remote": "Allow sending sequences to third-party services",
  "ui.runner.allow_remote_desc": "For example ColabFold's MSA server. When off, tools that need a remote service report “unavailable”.",
  "ui.pair.title": "Pair the local runner",
  "ui.pair.body": "This link comes from tcmstudio serve on your computer ({host}). Once connected, tools can run on your computer; the data does not pass through science.impf.ai.",
  "ui.web.label": "Web access",
  "ui.web.on": "Web on",
  "ui.web.off": "Web off",
  "ui.web.on_tip": "This project may reach online data sources (each new host is still approved)",
  "ui.web.off_tip": "This project does not reach the network (default)",
  "ui.web.on_toast": "Web access is on for this project. New hosts are still approved first.",
  "ui.web.off_toast": "Web access is off for this project.",
  "ui.web.desc_project": "Applies to “{name}”. New hosts are still approved first.",
  "ui.web.desc_default": "The default for new projects. New hosts are still approved first.",
  "ui.web.desc_long": "When on, the model may call online sources (literature, ChEMBL and others; they need the local runner). Off by default; each new host asks for approval first.",
  "ui.web.default_label": "Web access for new projects",
  "ui.web.default_desc": "Off by default. A project can turn it on for itself.",
  "ui.web.failed": "Web access was not changed: {message}. What is shown is what this browser holds.",
  "ui.net.offline": "This device is offline. Tools in this browser, the local runner and a local model still work; Tao-S1 and online sources wait for the connection.",
  "ui.net.online": "Back online.",
  "ui.offline.update": "A new version is ready. Reload to use it.",
  "ui.offline.reload": "Reload",
  "ui.browser.wasm": "WebAssembly: SIMD {simd}, threads {threads}",
  "ui.browser.threads_isolation": "need cross-origin isolation",
  "ui.browser.webnn_none": "WebNN: not in this browser",
  "ui.browser.webnn_failed": "WebNN: no context could be created",
  "ui.browser.webnn_contexts": "WebNN: contexts can be created ({list}). The browser does not report which processor runs a graph, so an NPU is unverified; no tool uses WebNN yet.",
  "ui.thread.label": "Conversation",
  "ui.thread.jump": "Jump to the latest",
  "ui.thread.generating": "Generating",
  "ui.thread.running_tools": plural("Running {n} tool", "Running {n} tools"),
  "ui.thread.waiting": "Waiting for your approval",
  "ui.thread.more_claims": plural("{n} more claim in the inspector", "{n} more claims in the inspector"),
  "ui.thread.open_models": "Open model settings",
  "ui.thread.error.model": "The model service did not finish this answer",
  "ui.thread.error.network": "Connection lost",
  "ui.thread.error.runtime": "Something failed to run",
  "ui.thread.model_refused": "The model declined this request.",
  "ui.thread.fallback": "This answer was generated by {model}.",
  "ui.thread.served_by": "served by {model}",
  "ui.thread.tool_count": plural("{n} tool call", "{n} tool calls"),
  "ui.thread.usage": "{input} input tokens · {output} output tokens",
  "ui.msg.edit": "Edit",
  "ui.msg.edit_note": "Saving starts a new branch from this message; the original conversation is kept (switch with ‹ ›).",
  "ui.msg.edit_send": "Save and send",
  "ui.msg.copy_md": "Copy (Markdown)",
  "ui.msg.regenerate": "Regenerate",
  "ui.branch.label": "Branch {i} of {n}",
  "ui.branch.prev": "Previous branch",
  "ui.branch.next": "Next branch",
  "ui.turn.done": "Answer complete",
  "ui.turn.done_tools": plural("Answer complete, {n} tool call", "Answer complete, {n} tool calls"),
  "ui.turn.failed_announce": "The answer did not complete",
  "ui.turn.tool_refused": "{name} refused",
  "ui.turn.save_failed": "Could not save this turn: {message}",
  "ui.run.thinking": "Thinking",
  "ui.run.thinking_note": "The model's thinking is not evidence",
  "ui.run.approval": "Approval",
  "ui.run.gate": "Release gate",
  "ui.run.answer": "Answer",
  "ui.run.kind.model": "model",
  "ui.run.kind.person": "you",
  "ui.run.kind.kernel": "kernel",
  "ui.run.kind.tool": "tool",
  "ui.run.gov.native": "native tool",
  "ui.run.gov.skill": "governed skill",
  "ui.run.gov.connector": "connector",
  "ui.run.gov.clinic": "clinic",
  "ui.run.gov.tcmdb": "TCM data hub",
  "ui.run.gov.study": "study design",
  "ui.run.gov.job": "job",
  "ui.run.gov.system": "system",
  "ui.run.live": "in progress",
  "ui.run.total": "{d} in all",
  "ui.run.tokens": "{input} in · {output} out tokens",
  "ui.evidence.count": plural("{n} evidence item", "{n} evidence items"),
  "ui.evidence.view": "View",
  "ui.evidence.list": "List",
  "ui.evidence.table": "Table",
  "ui.evidence.note": "Evidence kinds are types, not grades. The four quality dimensions are listed apart, with no total.",
  "ui.claims.filter": "Filter",
  "ui.claims.filter.all": "All",
  "ui.claims.filter.allowed": "Allowed",
  "ui.claims.filter.refused": "Refused",
  "ui.claims.filter.declaration": "Needs a limit",
  "ui.claims.filter.extrapolation": "Extrapolates",
  "ui.claims.note": "Judged by the kernel's rules, not by the model. Refused claims stay listed, with their codes.",
  "ui.claims.none_for_filter": "No claim matches this filter.",
  "ui.files.loading": "Loading…",
  "ui.files.inputs": "Inputs",
  "ui.files.inputs_note": "This project's files are kept in this browser (IndexedDB). Text files under 8 KB are sent to the selected model with every message; other files leave this device only when sent to the local runner.",
  "ui.files.outputs": "Outputs",
  "ui.files.no_inputs": "This project has no files yet.",
  "ui.files.no_outputs": "The tools of this turn declared no output files.",
  "ui.files.loc_browser": "Browser",
  "ui.files.loc_runner": "Local runner",
  "ui.files.digest_checked": "Hash checked",
  "ui.files.digest_checked_tip": "The runner checked this file against the sha256 recorded when the job was collected; it says the file is unchanged, not that the result is released",
  "ui.files.loc_both": "Browser + local runner",
  "ui.files.job": "Files of job {id}",
  "ui.files.preview": "Preview",
  "ui.files.download": "Download",
  "ui.files.preview_failed": "Cannot preview: {message}",
  "ui.files.no_bytes": "No file content",
  "ui.files.sandboxed": "The report is shown in an isolated frame; its scripts do not run.",
  "ui.files.pdf": "Download the PDF to view it.",
  "ui.files.truncated": "A large file ({size}); only the beginning is shown.",
  "ui.files.empty": "The file is empty.",
  "ui.files.table": "Table preview",
  "ui.files.rows": "First {shown} of {total} rows",
  "ui.files.more_items": plural("{n} more item", "{n} more items"),
  "ui.prov.pick": "Choose a tool run",
  "ui.prov.run": "This run",
  "ui.prov.tool": "Tool",
  "ui.prov.model": "Model",
  "ui.prov.where": "Where",
  "ui.prov.device": "Device",
  "ui.prov.runtime": "Runtime",
  "ui.prov.versions": "Versions",
  "ui.prov.started": "Started",
  "ui.prov.duration": "Duration",
  "ui.prov.attestation": "Audit",
  "ui.prov.durable": "Audit state",
  "ui.prov.durable_yes": "kept durably",
  "ui.prov.memory_only": "in memory only (not durable)",
  "ui.prov.release": "Release state",
  "ui.prov.sources": plural("{n} source card", "{n} source cards"),
  "ui.prov.artifact": "Artifact",
  "ui.prov.reproduce": "Reproduce",
  "ui.prov.reproduce_note": "Run this on a computer with tcmstudio installed to run the same code again. The output files' sha256 can be compared one by one; the hash of the whole result includes the run id, the time and the audit-chain position, so it differs on every run.",
  "ui.prov.copy_cmd": "Copy reproduce command",
  "ui.prov.raw": "Full result (JSON)",
  "ui.knowledge.title": "Knowledge files",
  "ui.knowledge.drop": "Drop files, or click to choose",
  "ui.knowledge.privacy": "Files are stored only in this browser and are not uploaded to science.impf.ai. Text files under 8 KB are sent to the selected model with every message in this project (for Tao-S1, through the science.impf.ai relay to the model service); they are the ones marked “Sent to the model”.",
  "ui.knowledge.none": "No knowledge files yet. Text files under 8 kB are added to the system prompt and sent to the model with every message; others are listed by name, size and hash.",
  "ui.knowledge.added": "Added “{name}” and hashed it",
  "ui.knowledge.uploaded": "uploaded",
  "ui.knowledge.from_tool": "made by a tool",
  "ui.knowledge.big": "over 200 MB",
  "ui.knowledge.send_runner": "Send to the local runner",
  "ui.knowledge.send_title": "Send to the local runner",
  "ui.knowledge.send_body": "Copy “{name}” into the local runner's workspace (127.0.0.1, your own computer) for tools that need files.",
  "ui.knowledge.send": "Send",
  "ui.knowledge.uploading": "Sending",
  "ui.knowledge.sent": "Sent “{name}” to the local runner",
  "ui.knowledge.hash_mismatch": "The runner's hash differs from the one computed in the browser; send the file again.",
  "ui.knowledge.delete_title": "Delete file",
  "ui.knowledge.delete_body": "Delete “{name}” from this browser. A copy sent to the local runner is not affected.",
  "ui.models.default_title": "Default model",
  "ui.models.tao_sub": "The research assistant of TCMScience Studio",
  "ui.models.is_default": "Default",
  "ui.models.set_default": "Make default",
  "ui.models.default_set": "Default model set",
  "ui.models.check_relay": "Check relay",
  "ui.models.relay_error": "The relay reports: {message}",
  "ui.models.limits": "Rate limits",
  "ui.models.limits_unknown": "Unknown (the relay did not answer)",
  "ui.models.per_minute": "{n} per minute",
  "ui.models.per_day": "{n} per day",
  "ui.models.tokens_per_day": "{n} tokens per day",
  "ui.models.max_output": "Max output per call",
  "ui.models.tokens": "{n} tokens",
  "ui.models.key": "Key",
  "ui.models.no_key": "None needed",
  "ui.models.yours": "Your model APIs",
  "ui.models.key_note": "Keys are stored only in this browser and never sent to science.impf.ai. Clearing browser data deletes them.",
  "ui.models.key_note_short": "Stored only in this browser; never sent to science.impf.ai.",
  "ui.models.remember": "Remember keys",
  "ui.models.remember_desc": "When off, keys live only in this tab and are gone when it closes.",
  "ui.models.forget_keys": "Delete all keys",
  "ui.models.forget_body": "Delete every API key you entered from this browser.",
  "ui.models.forget": "Delete",
  "ui.models.forgotten": "All keys deleted",
  "ui.models.configured": "Configured",
  "ui.models.configured_local": "Configured",
  "ui.models.no_key_set": "No key",
  "ui.models.not_set_local": "Not configured",
  "ui.models.base_url": "Endpoint",
  "ui.models.base_url_help": "Leave empty for the preset endpoint.",
  "ui.models.model": "Model",
  "ui.models.model_ph": "Model name",
  "ui.models.test": "Test connection",
  "ui.models.testing": "Testing: one small request that checks tool calling…",
  "ui.models.test_ok": "Connected; tool calling works",
  "ui.models.test_no_tools": "Connected, but the model did not call the tool: it may not support tool calling, so Studio's tools will not work with it",
  "ui.models.test_failed": "Connection failed",
  "ui.models.latency": "round trip {d}",
  "ui.models.first_token": "first response {d}",
  "ui.models.via_runner": "forwarded by the local runner",
  "ui.models.get_key": "Get a key",
  "ui.models.reveal": "Show or hide the key",
  "ui.models.custom": "Custom APIs",
  "ui.models.no_custom": "No custom endpoints yet. Any OpenAI-compatible or Anthropic-compatible service can be added.",
  "ui.models.add_openai": "Add an OpenAI-compatible endpoint",
  "ui.models.add_anthropic": "Add an Anthropic-compatible endpoint",
  "ui.models.format_openai": "OpenAI-compatible",
  "ui.models.format_anthropic": "Anthropic-compatible",
  "ui.models.label": "Name",
  "ui.models.max_tokens_param": "Max-output parameter",
  "ui.models.headers": "Extra headers (JSON)",
  "ui.models.extra_body": "Extra body fields (JSON)",
  "ui.models.delete_custom": "Delete this endpoint",
  "ui.models.local": "Local models",
  "ui.models.local_note": "When the page calls a model server on 127.0.0.1, the browser first asks whether this site may reach apps on this device; choose Allow. The server must also allow cross-origin calls (CORS), or connect the local runner to forward them.",
  "ui.models.detected_models": plural("{n} model", "{n} models"),
  "ui.models.not_answering": "not answering",
  "ui.models.advanced": "Advanced",
  "ui.models.route": "Model call route",
  "ui.models.route_direct": "Browser, directly",
  "ui.models.route_runner": "Through the local runner",
  "ui.models.route_help": "Auto: services that accept browser calls are called directly; local or CORS-blocked services go through the runner when it is connected. Tao-S1 always goes to the relay directly.",
  "ui.models.thinking": "Show thinking",
  "ui.models.thinking_desc": "Request and show the model's thinking when it supports it (collapsed by default). Thinking is not evidence.",
  "ui.models.max_tokens": "Max output (tokens)",
  "ui.models.max_tokens_help": "The output limit of each model call. Tao-S1 allows up to 8192.",
  "ui.models.max_steps": "Model calls per turn",
  "ui.models.max_steps_help": "How many times the model may be called in one answer (tool round trips included). Default 16.",
  "ui.models.temperature": "Temperature",
  "ui.models.temperature_default": "Default",
  "ui.models.temperature_help": "Leave empty for the service's default.",
  "ui.jobs.title": "Jobs",
  "ui.jobs.none": "No jobs on the local runner yet.",
  "ui.jobs.needs_runner": "Once the local runner is connected, its jobs are listed here (running, queued, collected).",
  "ui.job.connect_to_follow": "Connect the local runner to follow this job.",
  "ui.general.language": "Language",
  "ui.general.data": "Data and privacy",
  "ui.general.persistent": "Data is kept in this browser (IndexedDB)",
  "ui.general.memory": "Data is kept in memory only",
  "ui.general.privacy": "Projects, conversations, files and keys exist only in this browser on this device; nothing is synced to science.impf.ai. Your messages, tool results and project text files under 8 KB are sent to the selected model, though (for Tao-S1, through the science.impf.ai relay). Approved database queries pass through science.impf.ai to the selected source. Private windows and “clear site data” delete local data; export to keep it.",
  "ui.general.counts": "{projects} projects · {conversations} conversations",
  "ui.general.export_label": "Export a project",
  "ui.general.export": "Export",
  "ui.general.import": "Import a project",
  "ui.general.import_help": "Import an exported .json file as a new project; every file is checked against its hash.",
  "ui.general.import_btn": "Choose file",
  "ui.general.imported": "Project imported",
  "ui.general.clear": "Clear local data",
  "ui.general.clear_help": "Delete every Studio project, conversation, file, key and cache in this browser.",
  "ui.general.clear_btn": "Clear all",
  "ui.general.clear_title": "Clear local data",
  "ui.general.clear_body": "This deletes all Studio data in this browser and cannot be undone. Files on the local runner are not affected.",
  "ui.general.onboarding": "First-run guide",
  "ui.general.show_onboarding": "Show again",
  "ui.settings.tab.models": "Models",
  "ui.settings.tab.compute": "Compute",
  "ui.settings.tab.general": "General",
  "ui.settings.tab.shortcuts": "Shortcuts",
  "ui.shortcuts.title": "Keyboard shortcuts",
  "ui.shortcuts.lede": "⌘ and ⌥ on a Mac; Ctrl and Alt on Windows and Linux.",
  "ui.shortcuts.action": "Action",
  "ui.shortcuts.keys": "Keys",
  "ui.shortcuts.note": "Note",
  "ui.shortcuts.or": "or",
  "ui.shortcuts.palette": "Command palette / search",
  "ui.shortcuts.palette_note": "projects, conversations, commands, settings",
  "ui.shortcuts.new_chat": "New conversation",
  "ui.shortcuts.sidebar": "Show or hide the sidebar",
  "ui.shortcuts.inspector": "Show or hide the inspector",
  "ui.shortcuts.inspector_tab": "Inspector tab 1–5",
  "ui.shortcuts.focus": "Focus the message box",
  "ui.shortcuts.focus_note": "“/” works when you are not typing",
  "ui.shortcuts.send": "Send",
  "ui.shortcuts.send_note": "never while a Chinese input method is composing",
  "ui.shortcuts.newline": "New line",
  "ui.shortcuts.stop": "Stop generating",
  "ui.shortcuts.stop_note": "closes popovers and drawers first",
  "ui.shortcuts.edit_last": "Edit the last message",
  "ui.shortcuts.edit_last_note": "in an empty message box",
  "ui.shortcuts.copy_last": "Copy the last answer",
  "ui.shortcuts.attach": "Attach files",
  "ui.shortcuts.sheet": "This sheet",
  "ui.palette.label": "Command palette",
  "ui.palette.placeholder": "Search projects, conversations, messages or commands…",
  "ui.palette.results": "Results",
  "ui.palette.none": "Nothing found for “{q}”",
  "ui.palette.move": "move",
  "ui.palette.open": "open",
  "ui.palette.group.recent": "Recent conversations",
  "ui.palette.group.projects": "Projects",
  "ui.palette.group.conversations": "Conversations",
  "ui.palette.group.messages": "Messages",
  "ui.palette.group.commands": "Commands",
  "ui.palette.group.settings": "Settings and pages",
  "ui.palette.toggle_lang": "Switch language",
  "ui.palette.toggle_theme": "Switch appearance",
  "ui.palette.copy_last": "Copy the last answer",
  "ui.palette.connect_runner": "Connect the local runner",
  "ui.onb.title": "Getting started",
  "ui.onb.progress": "Steps",
  "ui.onb.step.language": "Language",
  "ui.onb.step.model": "Model",
  "ui.onb.step.compute": "Compute",
  "ui.onb.skip": "Skip",
  "ui.onb.back": "Back",
  "ui.onb.next": "Next",
  "ui.onb.start": "Start",
  "ui.onb.ready": "Ready",
  "ui.onb.optional": "Optional",
  "ui.onb.language_title": "Interface language",
  "ui.onb.language_text": "You can switch it at any time, top right. Herb and formula names stay in Chinese characters in both languages.",
  "ui.onb.model_title": "Model: Tao-S1 is ready",
  "ui.onb.model_more": "You can also connect your own model API (OpenAI, Anthropic, DeepSeek and others) or a local model; keys stay in this browser.",
  "ui.onb.compute_title": "Compute: on your own computer",
  "ui.onb.browser_text": "The browser is ready: TCMScience's Python code runs in this page (Pyodide), with nothing to install.",
  "ui.onb.runner_text": "Online sources and compatible GPU tools work in the browser. For large files, long jobs or native engines, run the local runner on your computer:",
  "ui.onb.runner_after": "It prints a pairing link; open it to connect. Your data stays on your computer.",
  "ui.catalog.search": "Search tools",
  "ui.catalog.search_ph": "Search: compatibility, targets, eGFR, reverse_complement…",
  "ui.catalog.lede": "{entries} tools and data sources; {core} core tools are offered to the model directly, the rest through catalog search.",
  "ui.catalog.lede_empty": "Tool catalog",
  "ui.catalog.empty_title": "The catalog is not loaded",
  "ui.catalog.empty": "This page was built without the catalog (runtime/catalog.json), and no local runner is connected. Once the runner is connected, every tool it can run is listed here.",
  "ui.catalog.categories": "Categories",
  "ui.catalog.all": "All",
  "ui.catalog.count": plural("{n} item", "{n} items"),
  "ui.catalog.count_top": "The {n} best matches",
  "ui.catalog.no_match": "No tool matches. Try other words (Chinese or English).",
  "ui.catalog.detail": "Tool details",
  "ui.catalog.missing": "Missing on the local runner: {deps}. Nothing approximate is substituted.",
  "ui.catalog.core": "Offered to the model directly as: {names}",
  "ui.catalog.params": "Parameters",
  "ui.catalog.param": "Parameter",
  "ui.catalog.type": "Type",
  "ui.catalog.desc": "Description",
  "ui.catalog.required": "required",
  "ui.catalog.default": "default",
  "ui.catalog.no_params": "No parameters.",
  "ui.catalog.example": "Example",
  "ui.catalog.skill": "Governed skill",
  "ui.catalog.version": "Version",
  "ui.catalog.pinned": "Pinned",
  "ui.catalog.claim_kinds": "Claim kinds it may produce",
  "ui.catalog.forbidden": "Forbidden claim kinds",
  "ui.catalog.max_tier": "Highest evidence tier",
  "ui.catalog.hosts": "Hosts reached",
  "ui.catalog.no_network": "No network",
  "ui.catalog.content_hash": "Content hash",
  "ui.catalog.try": "Try in a new conversation",
  "ui.catalog.try_prompt": "Use “{title}” ({id}) to",
  "ui.catalog.badge.browser": "Browser",
  "ui.catalog.badge.runner": "Runner",
  "ui.catalog.badge.network": "Network",
  "ui.catalog.badge.confirm": "Asks first",
  "ui.catalog.badge.job": "Job",
  "ui.catalog.badge.missing": "Missing deps",
  "ui.catalog.badge.now": "Runs now ({where})",
  "ui.catalog.badge.not_now": "Cannot run now",
  "ui.catalog.kind.native": "native tool",
  "ui.catalog.kind.skill": "governed skill",
  "ui.catalog.kind.connector": "connector",
  "ui.catalog.kind.clinic": "clinic",
  "ui.catalog.kind.tcmdb": "data hub",
  "ui.catalog.kind.study": "study design",
  "ui.catalog.kind.job": "job",
  "ui.catalog.kind.system": "system",
  "ui.about.title": "TCMScience Studio",
  "ui.about.lede": "The research workbench of TCMScience: a governed scientific agent. It calls TCMScience's tools and skills, and writes beside each result where it ran, what evidence it used, and which kinds of claim that evidence licenses.",
  "ui.about.what": "What it does",
  "ui.about.what.1": "Calls 150 native tools, the governed skills, the clinic, the TCM data hub and online sources from a conversation.",
  "ui.about.what.2": "The kernel judges every claim by its evidence kind: allowed, refused, or in need of a declared limit, with reason codes.",
  "ui.about.what.3": "Every tool run records where it ran, the device, the duration, input and output hashes and the composite version, so it can be reproduced.",
  "ui.about.what.4": "A refusal is a result: refused claims and calls are shown, never hidden.",
  "ui.about.where": "Where the computation and the data are",
  "ui.about.where.1": "Tools run in your browser (Pyodide WASM CPU, with WebGPU for compatible sequence statistics) or on your computer's local runner.",
  "ui.about.where.2": "science.impf.ai serves the page, Tao-S1 relay and bounded database gateway. It keeps no conversations. Approved online database requests are forwarded through the gateway to the chosen source.",
  "ui.about.where.3": "Reaching the network, sending data to a third-party service and starting a job all ask for your approval first.",
  "ui.about.where.4": "Your own model API keys stay in this browser; requests go straight to the service you chose (or through the local runner).",
  "ui.about.not": "What it does not claim",
  "ui.about.not.1": "No diagnosis or prescription. The clinic gives a draft for a licensed practitioner; signing it is a person's act.",
  "ui.about.not.2": "A classical record is not clinical evidence; no record is not safety.",
  "ui.about.not.3": "Network pharmacology, docking and target prediction are computational predictions: they license a mechanism hypothesis at most, and are not measurements.",
  "ui.about.not.4": "“Release authorized” says the six checks are met, not that a conclusion is true.",
  "ui.about.not.5": "The model's thinking and wording are not evidence; the kernel's rules decide what the evidence licenses.",
  "ui.about.privacy": "Privacy",
  "ui.about.privacy_text": "No account and no sync. Projects, conversations and files exist only in this browser on this device; export them under Settings → General to keep or move them. What goes to the model is the exception: your messages, tool results and project text files under 8 KB are sent to the selected model (for Tao-S1, through the science.impf.ai relay to the model service). Approved database requests and responses also pass through the site gateway without being stored.",
  "ui.about.links": "Links",
  "ui.about.link.project": "Project page",
  "ui.about.link.arena": "Arena: governed against ungoverned",
  "ui.about.link.github": "Source code on GitHub",
  "ui.about.versions": "Versions",
  "ui.about.catalog": "Tool catalog",
  "ui.about.catalog_n": "{core} core tools · {entries} entries",
  "ui.about.motto": "The model may reason. It does not define the laws of the laboratory.",
  // review fixes (web-ui)
  "ui.runner.paired": "Connected to the local runner ({host})",
  "ui.composer.store_failed": "The attachments could not be stored, so nothing was sent: {message}",
  "ui.composer.send_failed": "The message was not sent: {message}",
  "ui.composer.busy_elsewhere": "An answer is still being generated in “{title}”: one answer at a time. Wait for it, or stop it first.",
  "ui.composer.stop_other": "Stop that answer",
  "ui.composer.busy_tip": "An answer is being generated in another conversation",
  "ui.knowledge.to_model": "Sent to the model",
  "ui.knowledge.to_model_tip": "A text file under 8 KB: its full text is added to the system prompt and sent to the selected model with every message in this project.",
  "ui.code.UNPINNED": "Candidate Skill: no lockfile pins its version, so the run is recorded but its result is never released",
  "ui.kernel.original": "kernel text",
  "ui.kernel.original_tip": "The kernel's own record, shown as written",
  "ui.claim.basis_k": "Basis: ",
  "ui.claim.falsify_short_k": "Falsified by: ",
  "ui.release.unmet.schema_valid": "Schema not valid",
  "ui.release.unmet.evidence_verified": "Evidence not verified",
  "ui.release.unmet.outputs_verified": "Outputs not verified",
  "ui.release.unmet.execution_declared": "Execution not declared",
  "ui.release.unmet.execution_attested": "Execution not attested",
  "ui.release.unmet.release_authorized": "Release not authorized",
  "ui.release.unmet_k": "Not met: ",
  "ui.release.count": "Release state {passed}/{total}",
  "ui.artifact.chain_head": "runner's chain head (not this artifact's attestation)",
  "ui.artifact.candidate": "Candidate · unpinned, never released",
  "ui.artifact.candidate_tip": "No lockfile pins this Skill's version: the run is recorded, but its result is never released.",
  "ui.artifact.candidate_short": "candidate",
  "ui.artifact.status_k": "Artifact status",
  "ui.artifact.status_v": "{status} (workflow state, not human-validated)",
  "ui.evidence.select_row": "Select evidence {id}",
  "ui.tool.declined": "Not approved · not run",
  "ui.tool.clinic_draft": "Draft · for a licensed practitioner to review and sign",
  "ui.tool.interrupted": "Interrupted",
  "ui.tool.interrupted_line": "The page was closed or reloaded while this call ran: whether it finished is not known here.",
  "ui.tool.kernel_refusals": "Kernel refusals: {n}",
  "ui.thread.interrupted_title": "This turn was interrupted",
  "ui.thread.interrupted": "The page was reloaded or closed while the answer was being written. The text and tool results saved so far are kept below; a call without a result may or may not have finished. You can regenerate.",
  "ui.msg.you": "You said",
  "ui.msg.assistant": "Answer from {model}",
  "ui.model.relay_checking": "Checking the relay",
  "ui.onb.model_title.checking": "Model: checking Tao-S1",
  "ui.onb.model_title.ready": "Model: Tao-S1 is ready",
  "ui.onb.model_title.down": "Model: add a model first",
  "ui.onb.model_down": "Tao-S1's relay is not available now. Add a model API of your own (OpenAI, Anthropic, DeepSeek and others) or a local model to start; keys are stored only in this browser.",
  "ui.inspector.empty_turn.run": "This answer ran nothing; the whole conversation has {n} steps",
  "ui.inspector.empty_turn.evidence": "This answer has no evidence; the whole conversation has {n} items",
  "ui.inspector.empty_turn.claims": "This answer has no claims; the whole conversation has {n}",
  "ui.inspector.empty_turn.provenance": "This answer ran no tool; the whole conversation has {n} runs",
  "ui.inspector.show_all": "Show the whole conversation",
  "ui.prov.refusals": "Kernel refusals: {n}",
  "ui.prov.pinned": "Pinned",
};

let registered = false;
export function registerUiStrings() {
  if (registered) return;
  registered = true;
  registerStrings("zh", ZH);
  registerStrings("en", EN);
}
